from pathlib import Path
import re

p=Path('caso001-rev01/index.html')
s=p.read_text()

if 'P2.12D.6 · EVIDENCE RENDERER' in s:
    raise SystemExit('D6 already applied')

css=r'''
/* P2.12D.6 · EVIDENCE RENDERER */
.evidenceStage{margin:18px 0 10px;display:flex;align-items:center;gap:10px}.evidenceStage:after{content:"";height:1px;flex:1;background:linear-gradient(90deg,#715233,transparent)}.evidenceStage b{font-size:9px;letter-spacing:.18em;color:#d3a35b}.evidenceStage span{font-size:8px;letter-spacing:.08em;color:#7f7160}.evidenceDoc{position:relative;margin:10px 0;border:1px solid #65503a;background:#12100e;border-radius:5px;overflow:hidden;box-shadow:0 10px 24px rgba(0,0,0,.22)}.evidenceDoc.npc{border-style:dashed}.evidenceDoc.private{border-color:#8a6539;box-shadow:0 10px 26px rgba(0,0,0,.32),inset 0 0 0 1px rgba(209,162,89,.05)}.evHeader{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:8px 11px;border-bottom:1px solid #4b3929;background:#17130f}.evHeaderLeft{display:flex;gap:8px;align-items:center;min-width:0}.evGlyph{width:28px;height:28px;border:1px solid #71553a;display:grid;place-items:center;font-size:13px;color:#d4b37f;background:#0d0b09;flex:0 0 auto}.evMeta{display:grid;gap:2px;min-width:0}.evMeta b{font-size:9px;letter-spacing:.12em;color:#e2c18b}.evMeta span{font-size:7px;letter-spacing:.09em;color:#8e7d68}.evStageBadge{font:850 7px/1 ui-monospace,monospace;letter-spacing:.1em;border:1px solid #5d4934;color:#aa967d;padding:5px 6px;white-space:nowrap}.evBody{padding:13px}.evText{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.evFoot{display:flex;justify-content:space-between;gap:10px;margin-top:10px;padding-top:8px;border-top:1px solid rgba(72,55,39,.35);font-size:7px;letter-spacing:.11em;color:#6f6252}.ev-private .evHeader{background:linear-gradient(90deg,#251710,#15110e)}.ev-private .evStageBadge{border-color:#7b5b34;color:#e1b86e}.ev-private:before{content:"ARCHIVO PRIVADO";position:absolute;right:-27px;top:48px;transform:rotate(42deg);z-index:3;background:#6e2420;color:#f4dfc7;padding:3px 30px;font-size:6px;letter-spacing:.12em;font-weight:950;pointer-events:none}
/* testimonial */.ev-testimonial{background:linear-gradient(135deg,#d6c09d,#b99a72);color:#211a13;border-color:#806546}.ev-testimonial .evHeader{background:rgba(54,38,24,.12);border-color:#8d704d}.ev-testimonial .evGlyph{background:rgba(255,255,255,.15);border-color:#846746;color:#712721;font-family:Georgia,serif;font-size:20px}.ev-testimonial .evMeta b{color:#69231f}.ev-testimonial .evMeta span,.ev-testimonial .evStageBadge{color:#5d4a36;border-color:#8b6f4d}.evStatement{position:relative;padding:7px 8px 7px 30px;font-family:Georgia,serif;font-size:15px;line-height:1.62}.evStatement:before{content:"“";position:absolute;left:0;top:-10px;color:#872c27;font:52px/1 Georgia,serif;opacity:.78}.ev-testimonial .evFoot{color:#5f4a35;border-color:rgba(71,48,27,.2)}
/* digital */.ev-digital{border-color:#3c5a55;background:#08110f}.ev-digital .evHeader{background:#0c1714;border-color:#2e4c46}.ev-digital .evGlyph{border-color:#3a665e;color:#7fc5b8;background:#07100e}.ev-digital .evMeta b{color:#8ed5c7}.evDigitalScreen{background:repeating-linear-gradient(0deg,rgba(85,171,149,.025) 0 1px,transparent 1px 4px),#06100d;border:1px solid #24433d;padding:12px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#b5d9cf;font-size:12px;line-height:1.6}.evDigitalTop{display:flex;gap:5px;margin-bottom:9px}.evDigitalTop i{width:7px;height:7px;border-radius:50%;background:#3b655c}.evDigitalTop i:nth-child(2){opacity:.7}.evDigitalTop i:nth-child(3){opacity:.4}.ev-digital .evFoot{color:#638b81;border-color:#203d37}
/* access */.ev-access{border-color:#635a45;background:#11100c}.ev-access .evGlyph{color:#e2c46c}.evAccessRegister{display:grid;grid-template-columns:110px 1fr;border:1px solid #62563e;background:#17150e}.evAccessLabel{padding:12px;border-right:1px solid #62563e;background:repeating-linear-gradient(135deg,rgba(220,189,94,.04) 0 7px,transparent 7px 14px);font:900 9px/1.5 ui-monospace,monospace;color:#d7b85f;letter-spacing:.08em}.evAccessText{padding:12px;color:#ded5c2;line-height:1.55}.evAccessDot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#b99445;margin-right:6px;box-shadow:0 0 7px rgba(208,171,77,.35)}
/* physical */.ev-physical{background:#c9b38f;color:#241b13;border-color:#7b6042}.ev-physical .evHeader{background:#b49a74;border-color:#80694d}.ev-physical .evGlyph{background:#d8c5a6;color:#6f241f;border-color:#8c6d4a}.ev-physical .evMeta b{color:#6f241f}.ev-physical .evMeta span,.ev-physical .evStageBadge{color:#54412f;border-color:#856b4d}.evForensic{position:relative;border:1px solid #8c7557;background:linear-gradient(90deg,rgba(104,80,52,.05) 1px,transparent 1px),linear-gradient(rgba(104,80,52,.05) 1px,transparent 1px),#d7c5a7;background-size:18px 18px;padding:14px 14px 14px 18px;font-family:Georgia,serif;font-size:14px;line-height:1.55}.evForensic:after{content:"PERICIAL";position:absolute;right:10px;bottom:8px;border:2px solid rgba(113,36,31,.35);color:rgba(113,36,31,.5);padding:3px 7px;transform:rotate(-5deg);font:900 8px/1 sans-serif;letter-spacing:.12em}.ev-physical .evFoot{color:#5d4934;border-color:rgba(71,48,27,.2)}
/* temporal */.ev-temporal{border-color:#596277;background:#0e1015}.ev-temporal .evHeader{background:#11141b;border-color:#424b5e}.ev-temporal .evGlyph{color:#aebfe9;border-color:#4e5f84;background:#0c0f15}.ev-temporal .evMeta b{color:#b5c7ef}.evTemporal{position:relative;padding-left:24px;color:#d4dbee;line-height:1.55}.evTemporal:before{content:"";position:absolute;left:6px;top:2px;bottom:2px;width:1px;background:#5f719b}.evTemporal:after{content:"";position:absolute;left:2px;top:7px;width:9px;height:9px;border-radius:50%;background:#a9bbe4;box-shadow:0 0 0 3px #20293d}.evTimeTag{display:inline-block;margin-bottom:7px;font:850 8px/1 ui-monospace,monospace;letter-spacing:.12em;color:#8fa6dd}.ev-temporal .evFoot{color:#7281a3;border-color:#30384a}
/* motivational */.ev-motivational{background:linear-gradient(145deg,#d5c29f,#b69a73);color:#241a12;border-color:#806746}.ev-motivational .evHeader{background:rgba(79,49,30,.09);border-color:#8a704e}.ev-motivational .evGlyph{background:rgba(255,255,255,.13);color:#772a24;border-color:#8b6c4b}.ev-motivational .evMeta b{color:#702721}.ev-motivational .evMeta span,.ev-motivational .evStageBadge{color:#594531;border-color:#886d4c}.evMemo{background:rgba(250,239,215,.32);border-left:4px solid #7b2b25;padding:13px 14px;font-family:Georgia,serif;font-size:14px;line-height:1.58}.ev-motivational .evFoot{color:#5d4934;border-color:rgba(71,48,27,.2)}
/* generic */.ev-record .evGlyph{color:#c9ae82}.evGeneric{color:#ded1c0;line-height:1.55}.evidenceDoc.private.ev-testimonial,.evidenceDoc.private.ev-physical,.evidenceDoc.private.ev-motivational{box-shadow:0 10px 26px rgba(0,0,0,.3),inset 0 0 0 2px rgba(111,36,31,.12)}
@media(max-width:620px){.evHeader{align-items:flex-start}.evAccessRegister{grid-template-columns:1fr}.evAccessLabel{border-right:0;border-bottom:1px solid #62563e}.evBody{padding:11px}.evStatement{font-size:14px}.evStageBadge{font-size:6px}}
'''
anchor='/* P2.12D.5 · INVESTIGATION BOARD */'
if anchor not in s:
    raise SystemExit('D5 marker missing')
s=s.replace(anchor,css+'\n'+anchor,1)

helpers=r'''const REV01_EVIDENCE_META={
 testimonial:{label:'DECLARACIÓN',sub:'TESTIMONIO REGISTRADO',glyph:'“'},
 digital:{label:'EVIDENCIA DIGITAL',sub:'CAPTURA / LOG',glyph:'▣'},
 access:{label:'REGISTRO DE ACCESO',sub:'CONTROL DE INGRESO',glyph:'↳'},
 physical:{label:'FICHA PERICIAL',sub:'EVIDENCIA FÍSICA',glyph:'◆'},
 temporal:{label:'LÍNEA TEMPORAL',sub:'SECUENCIA / HORARIO',glyph:'◷'},
 motivational:{label:'DOCUMENTO CONTEXTUAL',sub:'MOTIVO / CONTEXTO',glyph:'▤'},
 record:{label:'REGISTRO DE EVIDENCIA',sub:'ARCHIVO DEL CASO',glyph:'•'}
};
function normalizeEvidenceType(value){const t=String(value||'record').trim().toLowerCase();const aliases={testimony:'testimonial',witness:'testimonial',statement:'testimonial',log:'digital',device:'digital',entry:'access',forensic:'physical',object:'physical',timeline:'temporal',time:'temporal',motive:'motivational',context:'motivational'};return REV01_EVIDENCE_META[t]?t:(aliases[t]||'record')}
function evidenceArtifact(type,text){const safe=esc(text||'Sin contenido registrado.');if(type==='testimonial')return `<div class="evStatement evText">${safe}</div>`;if(type==='digital')return `<div class="evDigitalScreen"><div class="evDigitalTop"><i></i><i></i><i></i></div><div class="evText">${safe}</div></div>`;if(type==='access')return `<div class="evAccessRegister"><div class="evAccessLabel"><span class="evAccessDot"></span>CONTROL<br>REGISTRO</div><div class="evAccessText evText">${safe}</div></div>`;if(type==='physical')return `<div class="evForensic evText">${safe}</div>`;if(type==='temporal')return `<div class="evTemporal"><span class="evTimeTag">SECUENCIA TEMPORAL</span><div class="evText">${safe}</div></div>`;if(type==='motivational')return `<div class="evMemo evText">${safe}</div>`;return `<div class="evGeneric evText">${safe}</div>`}
function renderEvidenceCard(item,opts={}){const payload=item?.payload||item||{},type=normalizeEvidenceType(payload.type||item?.type),meta=REV01_EVIDENCE_META[type]||REV01_EVIDENCE_META.record,stage=Number(payload.stage??item?.stage??opts.stage??1)||1,source=String(payload.source||item?.source||'').toLowerCase(),npc=source==='npc',privateCard=!!opts.privateCard,seq=Number(opts.seq||0),text=payload.text??item?.text??'';const top=privateCard?`SOLO VOS · ETAPA ${stage}`:`ETAPA ${stage}${npc?' · FUENTE NPC':''}`;return `<article class="evidenceDoc ev-${type}${npc?' npc':''}${privateCard?' private ev-private':''}"><header class="evHeader"><div class="evHeaderLeft"><span class="evGlyph">${esc(meta.glyph)}</span><span class="evMeta"><b>${esc(meta.label)}</b><span>${esc(meta.sub)}${seq?` · REGISTRO ${String(seq).padStart(2,'0')}`:''}</span></span></div><span class="evStageBadge">${esc(top)}</span></header><div class="evBody">${evidenceArtifact(type,text)}<div class="evFoot"><span>EXPEDIENTES · CASO 001</span><span>${privateCard?'LECTURA PRIVADA':'ARCHIVO COMPARTIDO'}</span></div></div></article>`}
'''

new_render=r'''function renderEvidence(){const events=evidenceEvents();if(!events.length){$('#publicEvidence').innerHTML='<div class="empty">Todavía no se liberaron evidencias.</div>';return}let html='',seq=0;for(let stage=1;stage<=3;stage++){const xs=events.filter(e=>Number(e.payload?.stage)===stage);if(!xs.length)continue;html+=`<div class="evidenceStage"><b>ETAPA ${stage}</b><span>${xs.length} REGISTRO${xs.length===1?'':'S'}</span></div>`+xs.map(e=>renderEvidenceCard(e,{seq:++seq})).join('')}$('#publicEvidence').innerHTML=html}
'''

pat=re.compile(r'function renderEvidence\(\)\{.*?\}\nfunction renderPrivate\(\)\{',re.S)
m=pat.search(s)
if not m:
    raise SystemExit('renderEvidence/renderPrivate anchor not found')
s=s[:m.start()]+helpers+new_render+'function renderPrivate(){'+s[m.end():]

new_private=r'''function renderPrivate(){if(!privateView){$('#roleBox').innerHTML='<div class="empty">La información privada aparecerá cuando comience la partida.</div>';$('#privateEvidence').innerHTML='';return}const r=privateView.role_payload||{},killer=privateView.role==='killer';$('#roleBox').innerHTML=`<div class="role ${killer?'killer':''}"><h3>${esc(r.role_label||'INVESTIGADOR')}</h3><p>${esc(r.objective||'')}</p>${killer&&privateView.impostor_truth?`<div class="privateTruth"><b>Tu verdad privada</b><p><b>Mentira central:</b> ${esc(privateView.impostor_truth.central_lie||'')}</p><p><b>Hecho real:</b> ${esc(privateView.impostor_truth.critical_event||'')}</p><p><b>Encubrimiento:</b> ${esc(privateView.impostor_truth.post_crime_action||'')}</p><p><b>Sabotajes:</b> ${esc((r.allowed_powers||[]).join(' · '))} (${Number(r.sabotage_tokens||0)} fichas)</p></div>`:''}</div>`;const xs=privateView.private_evidence||[];$('#privateEvidence').innerHTML=xs.length?`<div class="evidenceStage"><b>INFORMACIÓN PRIVADA</b><span>${xs.length} REGISTRO${xs.length===1?'':'S'}</span></div>`+xs.map((e,i)=>renderEvidenceCard(e,{privateCard:true,seq:i+1})).join(''):'<div class="empty">No tenés evidencia privada liberada en esta etapa.</div>'}
'''
pat2=re.compile(r'function renderPrivate\(\)\{.*?\}\nfunction renderTimeline\(\)\{',re.S)
m2=pat2.search(s)
if not m2:
    raise SystemExit('renderPrivate/renderTimeline anchor not found')
s=s[:m2.start()]+new_private+'function renderTimeline(){'+s[m2.end():]

p.write_text(s)
print('P2.12D.6 patch complete')
