/* VÍNCORES P1.8 · PREMIUM GUIDED FIELD */
(()=>{
'use strict';
if(window.__VINCORES_P18__)return;window.__VINCORES_P18__=true;window.VINCORES_RELEASE='P1.8';
const PHASES=['FOCO','REPRESENTAR','OBSERVAR','EXPLORAR','INTEGRAR'];
const STORE='vincores_p18_sessions_v1',PREF='vincores_p18_preferences_v1';
const now=()=>Date.now(), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const q=id=>document.getElementById(id);const qa=(sel,root=document)=>[...root.querySelectorAll(sel)];
const app=q('app'),right=document.querySelector('.right'),left=document.querySelector('.left'),stage=document.querySelector('.stageWrap');
if(!app||!right||!stage||typeof board==='undefined')return;
document.body.classList.add('p18-ready');
const prefs=(()=>{try{return {...{pauseSeconds:20,zoom:1},...JSON.parse(localStorage.getItem(PREF)||'{}')}}catch{return {pauseSeconds:20,zoom:1}}})();
const P={
 mode:'personal',phase:0,started:false,focus:'',clarityStart:null,clarityEnd:null,closingNote:'',
 asked:[],topicHistory:[],dismissed:[],events:[],notes:[],snapshots:[],pauseCount:0,moves:0,zoom:Number(prefs.zoom)||1,panX:0,panY:0,
 clean:false,observe:false,leftClosed:false,rightClosed:false,currentSuggestion:null,lastSuggestionAt:0,currentSceneKey:'unsaved',dirty:false,suppress:false,
 lastPointer:null,timer:null,pauseStartedAt:null
};
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return{}}}
function writeStore(){const all=readStore();all[P.currentSceneKey]={mode:P.mode,phase:P.phase,started:P.started,focus:P.focus,clarityStart:P.clarityStart,clarityEnd:P.clarityEnd,closingNote:P.closingNote,asked:P.asked,topicHistory:P.topicHistory,dismissed:P.dismissed,events:P.events.slice(-300),notes:P.notes,snapshots:P.snapshots.slice(-20),pauseCount:P.pauseCount,moves:P.moves,updatedAt:now()};localStorage.setItem(STORE,JSON.stringify(all))}
function loadSession(key){const all=readStore(),d=all[key];P.currentSceneKey=key;if(!d){P.mode='personal';P.phase=0;P.started=false;P.focus='';P.clarityStart=null;P.clarityEnd=null;P.closingNote='';P.asked=[];P.topicHistory=[];P.dismissed=[];P.events=[];P.notes=[];P.snapshots=[];P.pauseCount=0;P.moves=0}else Object.assign(P,d);renderGuide();renderJournal();updatePhase();}
let saveT;function persistSoon(){clearTimeout(saveT);saveT=setTimeout(writeStore,350)}
function timeLabel(ts){return new Date(ts).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}
function setDirty(v=true){P.dirty=v;const el=q('p18State');if(el){el.className='p18-state '+(v?'dirty':'saved');el.textContent=v?'Cambios sin guardar':'Guardado'}}
function eventLabel(e){const p=e.payload||{};const name=p.label?` · ${p.label}`:'';return ({session_started:'Comenzaste la práctica',focus_defined:'Definiste el foco',node_added:'Agregaste una figura',concept_added:'Agregaste un concepto',node_moved:'Moviste una figura',node_rotated:'Cambiaste orientación',relation_added:'Agregaste un vínculo',undo:'Volviste un paso',redo:'Rehiciste un cambio',stage_saved:'Guardaste una etapa',stage_loaded:'Abriste una etapa',pause_started:'Iniciaste una pausa',pause_finished:'Terminaste una pausa',pause_note:'Anotaste durante una pausa',note_added:'Agregaste una nota',snapshot:'Guardaste un momento',phase_changed:'Cambiaste de fase',node_removed:'Eliminaste un elemento'}[e.type]||e.type)+name}
function track(type,payload={}){if(P.suppress)return;const e={id:'ev-'+now().toString(36)+Math.random().toString(36).slice(2,6),type,payload,timestamp:now(),phase:PHASES[P.phase]};P.events.push(e);if(type==='node_moved')P.moves++;persistSoon();renderTimeline();setDirty(true);if(P.started&&!['note_added','pause_started','pause_finished'].includes(type))setTimeout(()=>refreshSuggestion(false),450)}
function currentFigures(){return qa('.node',board).filter(n=>n._meta?.kind==='figure')}
function currentSymbols(){return qa('.node',board).filter(n=>n._meta?.kind==='symbol')}
function context(){const figs=currentFigures(),syms=currentSymbols(),ev=P.events,latest=ev[ev.length-1]||null,recentMoves=ev.filter(x=>x.type==='node_moved'&&now()-x.timestamp<20000);return {figs,syms,rels:typeof relations!=='undefined'?relations:[],selected:typeof selected!=='undefined'?selected:null,latest,recentMoves,phase:PHASES[P.phase]}}
function geometry(){const figs=currentFigures();if(figs.length<2)return{};const pts=figs.map(n=>({n,x:parseFloat(n.style.left)||0,y:parseFloat(n.style.top)||0}));let closest=null,farthest=null;for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const d=Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y);const rec={a:pts[i],b:pts[j],d};if(!closest||d<closest.d)closest=rec;if(!farthest||d>farthest.d)farthest=rec}const cx=pts.reduce((s,p)=>s+p.x,0)/pts.length,cy=pts.reduce((s,p)=>s+p.y,0)/pts.length;let outlier=null;pts.forEach(p=>{const d=Math.hypot(p.x-cx,p.y-cy);if(!outlier||d>outlier.d)outlier={p,d}});return {closest,farthest,outlier,cx,cy}}
function allowedTopic(topic){const last=P.topicHistory.slice(-3);return !last.includes(topic)||P.events.slice(-3).some(e=>['node_moved','node_added','concept_added','relation_added'].includes(e.type))}
function candidates(){const c=context(),g=geometry(),list=[],latest=c.latest;const add=(id,topic,score,text,actions)=>{if(allowedTopic(topic))list.push({id,topic,score,text,actions})};
 if(c.recentMoves.length>=3)add('pause_fast','pause',100,'Hiciste varios movimientos seguidos. Antes de cambiar otra cosa, ¿querés mirar el campo completo unos segundos?',[['Pausa de campo','pause'],['Seguir explorando','continue']]);
 if(latest?.type==='undo')add('compare_undo','compare',95,'Volviste a una posición anterior. ¿Qué diferencia notaste entre las dos opciones?',[['Seguir observando','observe'],['Probar otra posición','move']]);
 if(latest?.type==='node_moved')add('reflect_move','movement',92,`Detenete un momento. ¿Qué cambió en el campo después de mover ${esc(latest.payload?.label||'esta figura')}?`,[['Seguir observando','observe'],['Volver al movimiento anterior','undo'],['Quiero probar otra posición','move']]);
 if(latest?.type==='concept_added')add('concept_position','concept',90,`Incorporaste ${esc(latest.payload?.label||'un concepto')}. ¿Qué te llama la atención de su posición dentro del campo?`,[['Seguir observando','observe'],['Mover el concepto','continue']]);
 if(latest?.type==='relation_added')add('relation_view','relation',89,`Elegiste representar un vínculo como ${esc(latest.payload?.label||'vínculo')}. ¿Qué cambia al mirarlo dentro del conjunto?`,[['Observar el vínculo','observe'],['Mirar el campo completo','clean']]);
 if(c.phase==='REPRESENTAR'&&c.figs.length===0)add('first_figure','represent',86,'¿Cuál es el primer elemento imprescindible para representar este tema?',[['Agregar una figura','add'],['Agregar un concepto','concept']]);
 if(c.phase==='REPRESENTAR'&&c.figs.length===1)add('need_more','represent',88,'¿Con esta figura alcanza para representar el tema o necesitás incorporar algo más?',[['Agregar algo','add'],['Por ahora alcanza','next']]);
 if(c.phase==='REPRESENTAR'&&c.figs.length>=2)add('representation_ready','represent',98,'¿El campo ya representa lo necesario para empezar a observar?',[['Sí, quiero observar','next'],['Agregar algo','add']]);
 if(c.figs.length>=7)add('simplify','simplify',78,'El campo ya tiene varios elementos. ¿Querés seguir observándolo completo o simplificarlo temporalmente?',[['Campo completo','observe'],['Simplificar','simplify']]);
 if(c.selected?._meta?.kind==='figure')add('selected','selected',72,`Elegiste ${esc(c.selected._meta.label||'esta figura')}. Antes de cambiarla, ¿qué querés observar de su posición actual?`,[['Distancia','distance'],['Dirección','direction'],['Quiero moverla','move']]);
 if(g.outlier&&g.outlier.d>34)add('outlier','periphery',68,'Una figura quedó bastante separada del conjunto. ¿Querés observar esa distancia antes de continuar?',[['Observar la distancia','distance'],['Mirar el conjunto','observe']]);
 if(g.closest&&g.closest.d<18)add('close_pair','distance',66,'Hay dos figuras muy próximas. Sin moverlas todavía, ¿qué notás al observar ese espacio?',[['Seguir observando','observe'],['Quiero comparar distancias','distance']]);
 if(c.figs.length>=2)add('distance','distance',58,'Sin mover nada todavía, mirá las distancias entre las figuras. ¿Hay alguna que te llame la atención?',[['Seguir observando','observe'],['Mirar direcciones','direction']]);
 if(c.phase==='OBSERVAR')add('observe_all','observe',54,'No cambies nada todavía. Mirá el campo como si lo vieras por primera vez. ¿Qué es lo primero que llama tu atención?',[['Seguir observando','observe'],['Quiero mover algo','explore']]);
 if(c.phase==='EXPLORAR')add('explore','explore',54,'Ahora podés probar un cambio sin tomarlo como definitivo. ¿Qué querés explorar?',[['Mover una figura','move'],['Agregar algo','add'],['Simplificar','simplify']]);
 if(c.phase==='INTEGRAR')add('integrate','integrate',70,'Antes de terminar, mirá el campo una vez más. ¿Qué querés conservar de esta práctica?',[['Escribir una nota','note'],['Cerrar práctica','close']]);
 if(!list.length)add('default','observe',30,'Mirá el campo completo unos segundos. ¿Qué aspecto querés observar ahora?',[['Distancias','distance'],['Direcciones','direction'],['Otra cosa','observe']]);return list.sort((a,b)=>b.score-a.score)}
function nextSuggestion(){const list=candidates();let s=list.find(x=>!P.asked.includes(x.id))||list[0];if(!s)return null;P.currentSuggestion=s;P.asked.push(s.id);if(P.asked.length>80)P.asked=P.asked.slice(-60);P.topicHistory.push(s.topic);if(P.topicHistory.length>20)P.topicHistory=P.topicHistory.slice(-20);P.lastSuggestionAt=now();persistSoon();return s}
function refreshSuggestion(force=false){if(!P.started)return;if(!force&&now()-P.lastSuggestionAt<7000)return;nextSuggestion();renderGuide()}
function updatePhase(){qa('#p18Phase span').forEach((s,i)=>s.classList.toggle('on',i<=P.phase));const k=q('p18Kicker');if(k)k.textContent=`${P.phase+1} DE 5 · ${PHASES[P.phase]}`}
function phaseTo(n){P.phase=Math.max(0,Math.min(4,n));track('phase_changed',{label:PHASES[P.phase]});P.currentSuggestion=null;P.lastSuggestionAt=0;nextSuggestion();renderGuide();updatePhase()}
function suggestionAction(code){switch(code){case'pause':startPause('facilitator');break;case'undo':typeof undo==='function'&&undo();break;case'next':phaseTo(P.phase+1);break;case'add':openLeftPanel();showToast?.('Elegí una figura o concepto');break;case'concept':document.getElementById('emotions')?.scrollIntoView({behavior:'smooth'});break;case'explore':phaseTo(3);showToast?.('Elegí una figura y probá una nueva posición');break;case'move':showToast?.('Elegí una figura y probá una nueva posición');break;case'simplify':handlePath('simplify');break;case'note':switchJournal('notes');q('p18QuickNote')?.focus();break;case'close':finishSession();break;case'clean':toggleClean(true);break;default:refreshSuggestion(true)} }
function guideHTML(){if(!P.started)return `<div class="p18-kicker">PRÁCTICA GUIADA</div><div class="p18-question">Un acompañamiento paso a paso, sin interpretar lo que ves.<small>VÍNCORES describe posiciones y movimientos; el significado lo construís vos.</small></div><div class="p18-actions"><button class="primary" data-gstart="personal">Acompañame · práctica personal</button><button data-gstart="facilitator">Estoy facilitando a otra persona</button></div>`;
 if(P.phase===0&&!P.focus)return `<div class="p18-phase" id="p18Phase">${PHASES.map(()=>'<span></span>').join('')}</div><div class="p18-kicker" id="p18Kicker"></div><div class="p18-question">¿Qué tema querés mirar hoy?</div><textarea id="p18FocusInput" class="p18-notearea" style="min-height:82px" placeholder="Una frase breve es suficiente"></textarea><div class="p18-actions" style="margin-top:7px"><button class="primary" data-focus-save>Continuar</button></div>`;
 const s=P.currentSuggestion||nextSuggestion();return `<div class="p18-phase" id="p18Phase">${PHASES.map(()=>'<span></span>').join('')}</div><div class="p18-kicker" id="p18Kicker"></div><div class="p18-question">${s?.text||'Mirá el campo completo.'}</div><div class="p18-actions">${(s?.actions||[]).map((a,i)=>`<button class="${i===0?'primary':''}" data-sact="${a[1]}">${a[0]}</button>`).join('')}<button class="soft" data-nextq>↻ Otra pregunta</button></div><button class="p18-stuck-link" data-stuck>No sé cómo seguir</button><div class="p18-guidenote">Podés salir de la práctica guiada cuando quieras. La escena no se pierde.</div>`}
function renderGuide(){const box=q('p18GuideBody');if(!box)return;box.innerHTML=guideHTML();updatePhase();qa('[data-gstart]',box).forEach(b=>b.onclick=()=>{P.mode=b.dataset.gstart;P.started=true;P.phase=0;P.clarityStart=null;track('session_started',{label:P.mode==='personal'?'Práctica personal':'Facilitación'});renderGuide()});q('p18FocusInput')&&(q('p18FocusInput').value=P.focus||'');document.querySelector('[data-focus-save]')?.addEventListener('click',()=>{const v=q('p18FocusInput').value.trim();if(!v)return showToast?.('Escribí una frase breve');P.focus=v;track('focus_defined',{label:v});phaseTo(1)});qa('[data-sact]',box).forEach(b=>b.onclick=()=>suggestionAction(b.dataset.sact));document.querySelector('[data-nextq]')?.addEventListener('click',()=>refreshSuggestion(true));document.querySelector('[data-stuck]')?.addEventListener('click',()=>openStuck());}
function journalKey(){return P.currentSceneKey||'unsaved'}
function addNote(text,source='manual'){text=String(text||'').trim();if(!text)return;P.notes.push({id:'n-'+now().toString(36),text,source,timestamp:now(),phase:PHASES[P.phase]});track(source==='pause'?'pause_note':'note_added',{label:text.slice(0,70)});renderJournal();persistSoon()}
function renderTimeline(){const box=q('p18Timeline');if(!box)return;const ev=P.events.filter(e=>!['node_selected'].includes(e.type)).slice(-70).reverse();box.innerHTML=ev.length?ev.map(e=>`<div class="p18-event"><b>${timeLabel(e.timestamp)} · ${esc(eventLabel(e))}</b>${e.type==='focus_defined'?`<span>${esc(e.payload.label||'')}</span>`:''}</div>`).join(''):'<div class="p18-event">Todavía no hay movimientos registrados en esta sesión.</div>'}
function summaryData(){return {figs:currentFigures().length,concepts:currentSymbols().length,rels:(typeof relations!=='undefined'?relations.length:0),moves:P.moves,pauses:P.pauseCount,notes:P.notes.length,stages:typeof stages!=='undefined'?stages.length:0}}
function renderSummary(){const box=q('p18Summary');if(!box)return;const d=summaryData();box.innerHTML=`<div class="p18-summary"><div class="p18-metric"><span>Tema</span><b>${esc(P.focus||'Sin definir')}</b></div><div class="p18-metric"><span>Campo actual</span><b>${d.figs} figuras · ${d.concepts} conceptos</b></div><div class="p18-metric"><span>Vínculos</span><b>${d.rels}</b></div><div class="p18-metric"><span>Movimientos</span><b>${d.moves}</b></div><div class="p18-metric"><span>Pausas</span><b>${d.pauses}</b></div><div class="p18-metric"><span>Etapas</span><b>${d.stages}</b></div><div class="p18-metric"><span>Notas</span><b>${d.notes}</b></div>${P.closingNote?`<div class="p18-event"><b>Quiero conservar</b>${esc(P.closingNote)}</div>`:''}<button class="btn" id="p18PrintSummary">Imprimir / guardar PDF</button></div>`;q('p18PrintSummary')?.addEventListener('click',printSummary)}
function renderJournal(){const notes=q('p18NotesList');if(notes)notes.innerHTML=P.notes.length?P.notes.slice().reverse().map(n=>`<div class="p18-event"><b>${timeLabel(n.timestamp)} · ${esc(n.phase)}</b>${esc(n.text)}</div>`).join(''):'<div class="p18-event">Todavía no escribiste notas.</div>';renderTimeline();renderSummary()}
function switchJournal(tab){qa('.p18-jtab').forEach(b=>b.classList.toggle('active',b.dataset.jtab===tab));qa('.p18-jview').forEach(v=>v.classList.toggle('active',v.dataset.jview===tab));if(tab==='history')renderTimeline();if(tab==='summary')renderSummary();switchRightTab('journal')}
function printSummary(){const d=summaryData(),div=document.createElement('div');div.className='p18-print';div.innerHTML=`<h1>VÍNCORES</h1><h2>Resumen de práctica</h2><p><b>Tema:</b> ${esc(P.focus||'Sin definir')}</p><p><b>Fecha:</b> ${new Date().toLocaleString('es-AR')}</p><hr><p>${d.figs} figuras · ${d.concepts} conceptos · ${d.rels} vínculos · ${d.moves} movimientos · ${d.pauses} pausas</p><h3>Notas</h3>${P.notes.map(n=>`<p><b>${timeLabel(n.timestamp)}</b> · ${esc(n.text)}</p>`).join('')||'<p>Sin notas.</p>'}<p style="margin-top:30px;color:#777">VÍNCORES registra observaciones y movimientos. No realiza diagnósticos ni interpreta el significado del campo.</p>`;document.body.appendChild(div);setTimeout(()=>{window.print();div.remove()},80)}
function finishSession(){P.phase=4;const txt=prompt('¿Qué querés conservar de esta práctica? Escribí una frase breve.',P.closingNote||'');if(txt!==null)P.closingNote=txt.trim();track('phase_changed',{label:'INTEGRAR'});switchJournal('summary');persistSoon();renderGuide()}
function openStuck(forced){const m=q('p18Stuck');m.classList.add('open');m.querySelector('h2').textContent='¿Qué te ayudaría ahora?';m.querySelector('p').textContent='No hay una respuesta correcta. Elegí una acción simple para continuar.';const c=context();const paths=[
 {id:'observe',icon:'👁',title:'Observar mejor',desc:'Cambiar la forma de mirar sin mover nada.'},
 {id:'move',icon:'↔',title:'Probar un movimiento',desc:'Cambiar una sola cosa y observar qué cambia.'},
 {id:'add',icon:'＋',title:'Agregar algo',desc:'Persona, rol, concepto o recurso.'},
 {id:'simplify',icon:'−',title:'Simplificar el campo',desc:'Ocultar temporalmente elementos, sin borrarlos.'},
 {id:'close',icon:'✓',title:'Empezar a cerrar',desc:'Pasar a integración y registrar lo observado.'}
 ];if(c.recentMoves.length>=3)paths.unshift({id:'pause',icon:'◉',title:'Hacer una pausa',desc:'Mirar el campo completo sin cambiar nada.'});if(c.figs.length<=1)paths.sort((a,b)=>a.id==='add'?-1:b.id==='add'?1:0);if(c.figs.length>=7)paths.sort((a,b)=>a.id==='simplify'?-1:b.id==='simplify'?1:0);q('p18Paths').innerHTML=paths.map(p=>`<button class="p18-path" data-path="${p.id}"><b>${p.icon} ${p.title}</b><span>${p.desc}</span></button>`).join('');qa('[data-path]',q('p18Paths')).forEach(b=>b.onclick=()=>{const id=forced||b.dataset.path;m.classList.remove('open');handlePath(id)})}
function handlePath(id){track('stuck_option_selected',{label:id});if(id==='pause')return startPause('stuck_menu');if(id==='close')return phaseTo(4);if(id==='add'){openLeftPanel();showToast?.('Agregá sólo lo que consideres necesario');return}if(id==='simplify')return openSimplify();P.currentSuggestion=null;P.lastSuggestionAt=0;refreshSuggestion(true);switchRightTab('guide')}
function openSimplify(){const nodes=qa('.node',board);if(nodes.length<3){showToast?.('El campo ya es simple');return}const m=q('p18Stuck');m.classList.add('open');m.querySelector('h2').textContent='Simplificar el campo';m.querySelector('p').textContent='Ocultá temporalmente lo que no necesites mirar ahora. Nada se borra.';const paths=q('p18Paths');paths.innerHTML=nodes.map(n=>`<button class="p18-path ${n.classList.contains('p18-temp-hidden')?'active':''}" data-hide-id="${esc(n._meta?.id||'')}"><b>${n.classList.contains('p18-temp-hidden')?'○':'●'} ${esc(n._meta?.label||'Elemento')}</b><span>${n.classList.contains('p18-temp-hidden')?'Oculto temporalmente':'Visible en el campo'}</span></button>`).join('')+`<button class="p18-path" id="p18RestoreHidden"><b>↺ Mostrar todo</b><span>Restaurar todos los elementos ocultos.</span></button><button class="p18-path" id="p18SimplifyDone"><b>✓ Listo</b><span>Volver al campo con esta vista simplificada.</span></button>`;qa('[data-hide-id]',paths).forEach(b=>b.onclick=()=>{const n=qa('.node',board).find(x=>x._meta?.id===b.dataset.hideId);if(!n)return;n.classList.toggle('p18-temp-hidden');track(n.classList.contains('p18-temp-hidden')?'elements_hidden':'elements_restored',{label:n._meta?.label||'Elemento'});renderRelations();openSimplify()});q('p18RestoreHidden').onclick=()=>{nodes.forEach(n=>n.classList.remove('p18-temp-hidden'));track('elements_restored',{label:'Mostrar todo'});renderRelations();openSimplify()};q('p18SimplifyDone').onclick=()=>{m.classList.remove('open');showToast?.('Vista simplificada lista')}}
function startPause(reason='manual'){if(q('p18Pause').classList.contains('open'))return;P.pauseCount++;P.pauseStartedAt=now();track('pause_started',{label:reason});q('p18Pause').classList.add('open');q('p18PauseQuestion').classList.add('hidden');q('p18PauseIntro').classList.remove('hidden');q('p18PauseNote').value='';let secs=Number(prefs.pauseSeconds)||20;q('p18PauseCount').textContent=`◉ ${secs} s`;clearInterval(P.timer);P.timer=setInterval(()=>{secs--;q('p18PauseCount').textContent=`◉ ${Math.max(0,secs)} s`;if(secs<=0){clearInterval(P.timer);q('p18PauseIntro').classList.add('hidden');q('p18PauseQuestion').classList.remove('hidden')}},1000)}
function endPause(){clearInterval(P.timer);q('p18Pause').classList.remove('open');const txt=q('p18PauseNote').value.trim();if(txt)addNote(txt,'pause');track('pause_finished');P.currentSuggestion=null;P.lastSuggestionAt=0;refreshSuggestion(true)}
function addSnapshot(){const name=prompt('¿Cómo querés llamar este momento?','Momento '+(P.snapshots.length+1));if(name===null)return;const snap={id:'snap-'+now().toString(36),name:name.trim()||'Momento '+(P.snapshots.length+1),timestamp:now(),state:typeof serializeState==='function'?clone(serializeState()):null};P.snapshots.push(snap);track('snapshot',{label:snap.name});showToast?.('Momento guardado');persistSoon()}
function applyNodeVisual(n){if(!n?._meta||n._meta.kind!=='figure')return;const b=n.querySelector('.figureBody');if(!b)return;const h=Number(n._meta.height)||58;const size=h<=50?'s':h<=63?'m':'l';const dims=n._meta.shape==='prism'?{s:[52,68],m:[61,86],l:[70,104]}:{s:[54,69],m:[64,88],l:[73,107]};const [w,hh]=dims[size];b.style.setProperty('--p18-w',w+'px');b.style.setProperty('--p18-h',hh+'px');b.style.height=hh+'px';n.dataset.p18size=size}
function enhanceAll(){qa('.node',board).forEach(applyNodeVisual)}
try{const p18BaseRenderRelations=renderRelations;renderRelations=function(){const original=relations;relations=original.filter(r=>{const a=nodeById(r.from),b=nodeById(r.to);return !a?.classList.contains('p18-temp-hidden')&&!b?.classList.contains('p18-temp-hidden')});p18BaseRenderRelations();relations=original}}catch{}
try{const oldRF=renderFigure;renderFigure=function(n){oldRF(n);applyNodeVisual(n)}}catch{}
try{const oldMF=makeFigure;makeFigure=function(shape,height,x=50,y=50,label='Sin nombre',opts={}){const n=oldMF(shape,height,x,y,label,opts);applyNodeVisual(n);if(!opts?.silent)track('node_added',{label:n?._meta?.label||label});return n}}catch{}
try{const oldMS=makeSymbol;makeSymbol=function(name,x=50,y=50,opts={}){const n=oldMS(name,x,y,opts);if(!opts?.silent)track('concept_added',{label:name});return n}}catch{}
try{const oldHL=handleLinkNode;handleLinkNode=function(n){const len=relations.length;oldHL(n);if(relations.length>len){const r=relations[relations.length-1],t=REL_TYPES[r.type]||REL_TYPES.bond;track('relation_added',{label:t.label})}}}catch{}
try{const oldUndo=undo;undo=function(){const n=history.length;oldUndo();if(history.length<n)track('undo')}}catch{}
try{const oldRedo=redo;redo=function(){const n=redoStack.length;oldRedo();if(redoStack.length<n)track('redo')}}catch{}
try{const oldSS=saveStage;saveStage=function(){const n=stages.length;oldSS();if(stages.length>n)track('stage_saved',{label:stages[stages.length-1]?.name})}}catch{}
try{const oldLS=loadStage;loadStage=function(i){oldLS(i);track('stage_loaded',{label:stages[i]?.name})}}catch{}
try{const oldRN=removeNode;removeNode=function(n){const label=n?._meta?.label;oldRN(n);if(label)track('node_removed',{label})}}catch{}
function applyZoom(){P.zoom=Math.max(.5,Math.min(1.5,P.zoom));board.style.transform=`translate(${P.panX}px,${P.panY}px) scale(${P.zoom})`;q('p18Zoom').textContent=Math.round(P.zoom*100)+'%';prefs.zoom=P.zoom;localStorage.setItem(PREF,JSON.stringify(prefs));setTimeout(()=>typeof renderRelations==='function'&&renderRelations(),60)}
function fitField(){const ns=qa('.node',board);if(!ns.length){P.zoom=1;P.panX=P.panY=0;return applyZoom()}const xs=ns.map(n=>parseFloat(n.style.left)||50),ys=ns.map(n=>parseFloat(n.style.top)||50);const w=Math.max(...xs)-Math.min(...xs)+24,h=Math.max(...ys)-Math.min(...ys)+28;P.zoom=Math.min(1.25,Math.max(.55,Math.min(100/w,100/h)));P.panX=P.panY=0;applyZoom()}
function toggleClean(force){P.clean=force===undefined?!P.clean:force;app.classList.toggle('p18-clean',P.clean);q('p18CleanBtn')?.classList.toggle('active',P.clean);setTimeout(()=>typeof renderRelations==='function'&&renderRelations(),180)}
function toggleObserve(){P.observe=!P.observe;app.classList.toggle('p18-observe',P.observe);q('p18ObserveBtn')?.classList.toggle('active',P.observe);showToast?.(P.observe?'Modo observación':'Edición activa')}
function toggleFullscreen(){if(!document.fullscreenElement)stage.requestFullscreen?.();else document.exitFullscreen?.()}
function openLeftPanel(){if(innerWidth<=980){app.classList.add('p18-mobile-left');app.classList.remove('p18-mobile-right')}else{P.leftClosed=false;app.classList.remove('p18-left-closed')}}
function openRightPanel(){if(innerWidth<=980){app.classList.add('p18-mobile-right');app.classList.remove('p18-mobile-left')}else{P.rightClosed=false;app.classList.remove('p18-right-closed')}}
function switchRightTab(tab){openRightPanel();qa('.p18-tab').forEach(b=>b.classList.toggle('active',b.dataset.rtab===tab));const piece=right.querySelector('.p18-piece-panel'),guide=q('p18GuidePanel'),journal=q('p18JournalPanel');piece?.classList.toggle('p18-hidden',tab!=='piece');guide?.classList.toggle('active',tab==='guide');journal?.classList.toggle('active',tab==='journal');if(tab==='guide')renderGuide();if(tab==='journal')renderJournal()}
function buildUI(){const piece=right.querySelector('.panel');piece?.classList.add('p18-piece-panel');right.insertAdjacentHTML('afterbegin',`<div class="p18-tabs"><button class="p18-tab active" data-rtab="piece">Pieza</button><button class="p18-tab" data-rtab="guide">Guía</button><button class="p18-tab" data-rtab="journal">Bitácora</button></div>`);right.insertAdjacentHTML('beforeend',`<div class="panel p18-guide-panel" id="p18GuidePanel"><div id="p18GuideBody"></div></div><div class="panel p18-journal-panel" id="p18JournalPanel"><div class="p18-jtabs"><button class="p18-jtab active" data-jtab="notes">Notas</button><button class="p18-jtab" data-jtab="history">Historia</button><button class="p18-jtab" data-jtab="summary">Resumen</button></div><div class="p18-jview active" data-jview="notes"><textarea class="p18-notearea" id="p18QuickNote" placeholder="Escribí algo que quieras conservar..."></textarea><div class="p18-note-row"><button class="btn primary" id="p18AddNote">Guardar nota</button><button class="btn" id="p18Snapshot">📷 Momento</button></div><div id="p18NotesList" class="p18-timeline" style="margin-top:8px"></div><div class="p18-privacy">Se guarda localmente junto a tu sesión. Evitá registrar información sensible en equipos compartidos.</div></div><div class="p18-jview" data-jview="history"><div id="p18Timeline" class="p18-timeline"></div></div><div class="p18-jview" data-jview="summary"><div id="p18Summary"></div></div></div>`);
 const bar=document.createElement('div');bar.className='p18-fieldbar';bar.innerHTML=`<div class="p18-group"><button class="p18-mini" id="p18LeftBtn" title="Agregar">＋</button><button class="p18-mini" id="p18ZoomOut">−</button><span class="p18-zoom" id="p18Zoom">100%</span><button class="p18-mini" id="p18ZoomIn">＋</button><button class="p18-mini" id="p18Fit" title="Ajustar al contenido">◎</button></div><div class="p18-group"><span class="p18-state saved" id="p18State">Guardado</span><button class="p18-mini" id="p18ObserveBtn" title="Modo observación">👁</button><button class="p18-mini" id="p18PauseBtn" title="Pausa de campo">◉</button><button class="p18-mini" id="p18CleanBtn" title="Campo limpio">◫</button><button class="p18-mini" id="p18FullBtn" title="Pantalla completa">⛶</button></div>`;stage.insertBefore(bar,stage.querySelector('.boardFrame'));
 document.body.insertAdjacentHTML('beforeend',`<button class="p18-side-tab left" id="p18LeftTab">AGREGAR</button><button class="p18-side-tab right" id="p18RightTab">GUÍA</button><div class="p18-mobilebar" id="p18MobileBar"><button data-mobile="left"><span>＋</span>Agregar</button><button data-mobile="field"><span>◎</span>Campo</button><button data-mobile="guide"><span>✦</span>Guía</button><button data-mobile="journal"><span>✎</span>Bitácora</button><button data-mobile="more"><span>•••</span>Más</button></div><div class="p18-modal" id="p18Stuck"><div class="p18-sheet"><div class="p18-kicker">OTRA FORMA DE MIRAR</div><h2>¿Qué te ayudaría ahora?</h2><p>No hay una respuesta correcta. Elegí una acción simple para continuar.</p><div class="p18-paths" id="p18Paths"></div><div class="p18-modal-actions"><button class="btn" id="p18StuckClose">Volver</button><button class="btn" id="p18PauseFromStuck">◉ Hacer una pausa</button></div></div></div><div class="p18-pause" id="p18Pause"><div class="p18-pause-card"><div id="p18PauseIntro"><div class="p18-kicker">PAUSA DE CAMPO</div><h2>No cambies nada por un momento.</h2><p>Mirá el campo completo. Podés hacer zoom o recorrerlo, pero no necesitás resolver nada ahora.</p><div class="p18-count" id="p18PauseCount">◉ 20 s</div></div><div class="hidden" id="p18PauseQuestion"><div class="p18-kicker">VOLVÉ A MIRAR</div><h2>¿Qué notás ahora que antes no estabas mirando?</h2><textarea id="p18PauseNote" placeholder="Podés escribir una frase breve o dejarlo en blanco."></textarea><div class="p18-pause-actions"><button class="btn primary" id="p18PauseEnd">Volver a editar</button><button class="btn" id="p18PauseExtend">+20 s</button></div></div></div></div>`);
 qa('[data-rtab]').forEach(b=>b.onclick=()=>switchRightTab(b.dataset.rtab));qa('.p18-jtab').forEach(b=>b.onclick=()=>switchJournal(b.dataset.jtab));q('p18AddNote').onclick=()=>{addNote(q('p18QuickNote').value);q('p18QuickNote').value=''};q('p18Snapshot').onclick=addSnapshot;
 q('p18ZoomOut').onclick=()=>{P.zoom-=.1;applyZoom()};q('p18ZoomIn').onclick=()=>{P.zoom+=.1;applyZoom()};q('p18Fit').onclick=fitField;q('p18CleanBtn').onclick=()=>toggleClean();q('p18ObserveBtn').onclick=toggleObserve;q('p18PauseBtn').onclick=()=>startPause('manual');q('p18FullBtn').onclick=toggleFullscreen;q('p18LeftBtn').onclick=openLeftPanel;
 q('p18LeftTab').onclick=()=>{P.leftClosed=!P.leftClosed;app.classList.toggle('p18-left-closed',P.leftClosed)};q('p18RightTab').onclick=()=>{P.rightClosed=!P.rightClosed;app.classList.toggle('p18-right-closed',P.rightClosed);if(!P.rightClosed)switchRightTab('guide')};q('p18StuckClose').onclick=()=>q('p18Stuck').classList.remove('open');q('p18PauseFromStuck').onclick=()=>{q('p18Stuck').classList.remove('open');startPause('stuck_menu')};q('p18PauseEnd').onclick=endPause;q('p18PauseExtend').onclick=()=>{q('p18PauseQuestion').classList.add('hidden');q('p18PauseIntro').classList.remove('hidden');let secs=20;q('p18PauseCount').textContent=`◉ ${secs} s`;clearInterval(P.timer);P.timer=setInterval(()=>{secs--;q('p18PauseCount').textContent=`◉ ${Math.max(0,secs)} s`;if(secs<=0){clearInterval(P.timer);q('p18PauseIntro').classList.add('hidden');q('p18PauseQuestion').classList.remove('hidden')}},1000)};
 qa('[data-mobile]').forEach(b=>b.onclick=()=>{const x=b.dataset.mobile;if(x==='left')openLeftPanel();if(x==='field'){app.classList.remove('p18-mobile-left','p18-mobile-right');fitField()}if(x==='guide')switchRightTab('guide');if(x==='journal')switchRightTab('journal');if(x==='more')openStuck()});
}
function wireP18Backup(){
 const exp=q('sceneLibraryExport'),imp=q('sceneLibraryImport');
 if(exp)exp.onclick=()=>{
  let scenes=[];try{scenes=JSON.parse(localStorage.getItem('vincores_scene_library_v1')||'[]')}catch{}
  const payload={type:'VINCORES_BACKUP',version:2,exportedAt:new Date().toISOString(),scenes,p18Sessions:readStore()};
  const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');
  a.href=url;a.download='vincores-respaldo-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)
 };
 if(imp)imp.onchange=async e=>{
  const f=e.target.files?.[0];if(!f)return;
  try{
   const p=JSON.parse(await f.text());if(p?.type!=='VINCORES_BACKUP'||!Array.isArray(p.scenes))throw new Error('Archivo de respaldo no válido.');
   if(!confirm('¿Importar '+p.scenes.length+' escenas? Se combinarán con las actuales.'))return;
   let lib=[];try{lib=JSON.parse(localStorage.getItem('vincores_scene_library_v1')||'[]')}catch{}
   const ids=new Set(lib.map(x=>x.id)),map={};
   for(const raw of p.scenes){const x=JSON.parse(JSON.stringify(raw)),old=x.id||('legacy-'+Math.random());if(!x.id||ids.has(x.id))x.id='sc-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);ids.add(x.id);map[old]=x.id;lib.push(x)}
   localStorage.setItem('vincores_scene_library_v1',JSON.stringify(lib));
   if(p.p18Sessions&&typeof p.p18Sessions==='object'){
    const sessions=readStore();for(const [old,val] of Object.entries(p.p18Sessions)){const key=map[old]||old;if(!sessions[key])sessions[key]=val}localStorage.setItem(STORE,JSON.stringify(sessions))
   }
   showToast?.('Respaldo importado');q('sceneLibraryOverlay')?.classList.remove('open');setTimeout(()=>q('loadBtn')?.click(),120)
  }catch(err){alert(err.message||'No pude importar el respaldo.')}finally{e.target.value=''}
 }
}

function wireEvents(){let viewDrag=null;board.addEventListener('pointerdown',e=>{if(!e.target.closest('.node')&&P.zoom>1){viewDrag={id:e.pointerId,x:e.clientX,y:e.clientY,px:P.panX,py:P.panY};board.setPointerCapture?.(e.pointerId);e.preventDefault();return}const n=e.target.closest('.node');if(!n)return;P.lastPointer={id:n._meta?.id,x:parseFloat(n.style.left)||0,y:parseFloat(n.style.top)||0,label:n._meta?.label||'Figura'}},true);board.addEventListener('pointerup',e=>{const n=e.target.closest('.node');if(!n||!P.lastPointer||P.lastPointer.id!==n._meta?.id)return;const x=parseFloat(n.style.left)||0,y=parseFloat(n.style.top)||0,d=Math.hypot(x-P.lastPointer.x,y-P.lastPointer.y);if(d>2.5)track('node_moved',{label:n._meta?.label||P.lastPointer.label,from:{x:P.lastPointer.x,y:P.lastPointer.y},to:{x,y}});P.lastPointer=null},true);board.addEventListener('pointermove',e=>{if(!viewDrag||viewDrag.id!==e.pointerId)return;P.panX=Math.max(-420,Math.min(420,viewDrag.px+e.clientX-viewDrag.x));P.panY=Math.max(-320,Math.min(320,viewDrag.py+e.clientY-viewDrag.y));applyZoom()});board.addEventListener('pointerup',e=>{if(viewDrag?.id===e.pointerId)viewDrag=null});board.addEventListener('pointercancel',()=>viewDrag=null);q('rotation')?.addEventListener('change',()=>{if(selected?._meta)track('node_rotated',{label:selected._meta.label})});q('saveBtn')?.addEventListener('click',()=>{setTimeout(()=>setDirty(false),80)});q('loadBtn')?.addEventListener('click',()=>setTimeout(enhanceAll,120));q('clearBtn')?.addEventListener('click',()=>setTimeout(()=>track('field_cleared'),80));document.addEventListener('keydown',e=>{const tag=e.target?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag)||e.target?.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected?.()}else if(e.key==='0'){e.preventDefault();fitField()}else if(e.key.toLowerCase()==='f'){e.preventDefault();toggleClean()}else if(e.key==='Escape'){q('p18Stuck')?.classList.remove('open');app.classList.remove('p18-mobile-left','p18-mobile-right');if(P.clean)toggleClean(false)}});window.addEventListener('resize',()=>{setTimeout(()=>{typeof renderRelations==='function'&&renderRelations()},100)});const mo=new MutationObserver(enhanceAll);mo.observe(board,{childList:true,subtree:true});
}
const __p181BaseAddFigure=window.addFigure;
if(typeof __p181BaseAddFigure==="function")window.addFigure=function(){const out=__p181BaseAddFigure.apply(this,arguments);if(!P.started)setTimeout(()=>switchRightTab("piece"),0);return out};
const __p181BaseSelectNode=window.selectNode;
if(typeof __p181BaseSelectNode==="function")window.selectNode=function(n){const out=__p181BaseSelectNode.apply(this,arguments);if(n?._meta?.kind==="figure"&&!P.started)setTimeout(()=>switchRightTab("piece"),0);return out};
buildUI();wireEvents();enhanceAll();applyZoom();renderGuide();renderJournal();wireP18Backup();
let lastScene=window.vincoresCurrentSceneId||'unsaved';loadSession(lastScene);setInterval(()=>{const key=window.vincoresCurrentSceneId||'unsaved';if(key!==lastScene){writeStore();const all=readStore();if(!all[key]&&all[lastScene]){all[key]=JSON.parse(JSON.stringify(all[lastScene]));all[key].updatedAt=now();localStorage.setItem(STORE,JSON.stringify(all))}lastScene=key;loadSession(key);setTimeout(enhanceAll,100)}},600);
setTimeout(()=>{const btn=q('enterBtn');if(btn)btn.addEventListener('click',()=>setTimeout(()=>{enhanceAll();fitField();if(innerWidth>980)switchRightTab('guide');else app.classList.remove('p18-mobile-left','p18-mobile-right')},300));},0);
window.VincoresP18={state:P,track,suggest:()=>{P.currentSuggestion=null;P.lastSuggestionAt=0;refreshSuggestion(true)},pause:startPause,fit:fitField,openStuck,addNote};
})();
