function renderDiffs(){document.getElementById('diffOpts').innerHTML=diffs.map(x=>`<div class="option ${S.difficulty===x[0]?'selected':''}" onclick="S.difficulty='${x[0]}';renderDiffs()"><div class="option-icon">${x[1]}</div><div><strong>${x[2]}</strong><small>${x[3]}</small></div><div class="check">${S.difficulty===x[0]?'✓':''}</div></div>`).join('')}
function teamMode(){return S.mode==='EQUIPOS'}
function teamOfPlayer(i){return S.teams[S.players[i]?.team===1?1:0]}
function teamName(i){return escapeHtml(S.teams[i]?.name||('Equipo '+(i?'B':'A')))}
function setTeamName(i,v){S.teams[i].name=(v||'').slice(0,22);savePrefs()}
function setPlayerTeam(i,t){S.players[i].team=t===1?1:0;renderPlayers()}
function renderPlayers(){let team=teamMode(),cfg=document.getElementById('teamConfig');cfg.classList.toggle('hidden',!team);document.getElementById('playersTitle').textContent=team?'Armá los dos equipos':'¿Quiénes juegan?';document.getElementById('playersSubtitle').textContent=team?'Asigná cada jugador al Equipo A o B.':'Hasta 8 jugadores.';if(team){document.getElementById('teamNameA').value=S.teams[0].name;document.getElementById('teamNameB').value=S.teams[1].name}let el=document.getElementById('playersList');el.innerHTML=S.players.map((p,i)=>team?`<div class="player-team"><input value="${escapeHtml(p.name)}" oninput="S.players[${i}].name=this.value"><button class="team-toggle ${p.team===0?'a':''}" onclick="setPlayerTeam(${i},0)">A</button><button class="team-toggle ${p.team===1?'b':''}" onclick="setPlayerTeam(${i},1)">B</button><button class="btn btn-danger" style="grid-column:1/-1;min-height:40px" onclick="removePlayer(${i})">QUITAR</button></div>`:`<div class="player-line"><input value="${escapeHtml(p.name)}" oninput="S.players[${i}].name=this.value"><button class="btn btn-danger" onclick="removePlayer(${i})">×</button></div>`).join('')}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addPlayer(){if(S.players.length<8)S.players.push(normPlayer({name:'Jugador '+(S.players.length+1),team:S.players.length%2},S.players.length));renderPlayers()}
function removePlayer(i){if(S.players.length>2)S.players.splice(i,1);renderPlayers()}
function savePlayers(){S.players=S.players.map((p,i)=>({...normPlayer(p,i),name:(p.name||'').trim()||'Jugador '+(i+1)}));if(teamMode()){let a=S.players.filter(p=>p.team===0).length,b=S.players.filter(p=>p.team===1).length;if(!a||!b){alert('Modo Equipos necesita al menos un jugador en cada equipo.');return false}S.teams[0].name=(S.teams[0].name||'').trim()||'Equipo A';S.teams[1].name=(S.teams[1].name||'').trim()||'Equipo B'}return true}
function reorderTeamPlayers(){if(!teamMode())return;let a=S.players.filter(p=>p.team===0),b=S.players.filter(p=>p.team===1),mix=[];for(let i=0;i<Math.max(a.length,b.length);i++){if(a[i])mix.push(a[i]);if(b[i])mix.push(b[i])}S.players=mix}
function formatLabel(){return S.playFormat==='FISICA'?'🧱 Torre Física':'📱 Solo Digital'}
function pointsMode(){return S.mode==='PUNTOS'||S.mode==='FINAL'||S.mode==='EQUIPOS'}
function addPoints(i,pts){if(!S.players[i])return;S.players[i].score+=pts;if(teamMode()){let t=S.players[i].team===1?1:0;S.teams[t].score+=pts}}
function teamLeader(){let a=S.teams[0].score,b=S.teams[1].score;return a===b?-1:(a>b?0:1)}
function opposingPlayers(i=S.current){if(!teamMode())return S.players.map((p,idx)=>idx).filter(idx=>idx!==i);let my=S.players[i]?.team;return S.players.map((p,idx)=>({p,idx})).filter(x=>x.idx!==i&&x.p.team!==my).map(x=>x.idx)}
function teammatePlayers(i=S.current,includeSelf=true){if(!teamMode())return S.players.map((p,idx)=>idx).filter(idx=>includeSelf||idx!==i);let my=S.players[i]?.team;return S.players.map((p,idx)=>({p,idx})).filter(x=>x.p.team===my&&(includeSelf||x.idx!==i)).map(x=>x.idx)}
function renderSummary(){let teamInfo=teamMode()?`<div class="score-row"><span>${teamName(0)}</span><b>${S.players.filter(p=>p.team===0).map(p=>escapeHtml(p.name)).join(', ')}</b></div><div class="score-row"><span>${teamName(1)}</span><b>${S.players.filter(p=>p.team===1).map(p=>escapeHtml(p.name)).join(', ')}</b></div>`:`<div class="score-row"><span>Jugadores</span><b>${S.players.map(x=>escapeHtml(x.name)).join(', ')}</b></div>`;document.getElementById('summaryBox').innerHTML=`<div class="score-row"><span>Formato</span><b class="score-value">${formatLabel()}</b></div><div class="score-row"><span>Modo</span><b>${S.mode}</b></div><div class="score-row"><span>Dificultad</span><b>${S.difficulty}</b></div>${teamInfo}<div class="score-row"><span>Biblioteca</span><b>162 + 60</b></div><div class="score-row"><span>Powers Engine</span><b class="score-value">ACTIVO</b></div>`}
function startGame(){S.players=S.players.map((p,i)=>({...normPlayer(p,i),score:0,lives:3,powers:[],redTurns:0}));if(teamMode()){S.teams.forEach(t=>t.score=0);reorderTeamPlayers();let a=S.players.filter(p=>p.team===0).length;S.teamCursors=[a?1%a:0,0]}S.current=0;S.used=[];S.usedPen=[];S.recentBlocks=[];S.currentContent=null;S.currentBlock=null;S.turnCount=0;S.turnCtx=null;S.lastOutcome=null;S.shootout=null;S.tiebreakQueue=[];S.activePenalty=null;S.started=true;save();playFx('whistle');go('turn')}
