function afterResult(){let ctx=S.turnCtx||{};if(ctx.postDone)return nextTurn();if(S.playFormat==='DIGITAL'&&S.mode==='PUNTOS'&&Math.max(...S.players.map(p=>p.score))>=10)return endGameByScore();if(S.playFormat==='DIGITAL'&&teamMode()&&Math.max(...S.teams.map(t=>t.score))>=10)return endTeamGameByScore();ctx.postDone=true;S.turnCtx=ctx;if(S.mode==='ELIMINACION'&&S.players[ctx.owner]?.lives<=0)return nextTurn();if(ctx.eventDisabled)return nextTurn();if(ctx.event==='ROJA'&&S.lastOutcome?.ok){ctx.powerStage='POST_RED';return chooseRedTarget()}if(ctx.event==='PENALES'){ctx.powerStage='POST_PENALES';return chooseMiniRival('PENALES')}if(ctx.event==='FINAL'){ctx.powerStage='POST_FINAL';return chooseMiniRival('FINAL')}nextTurn()}
function chooseRedTarget(){showPower('🟥','ROJA','Elegí un rival. En su próximo turno jugará sin poderes especiales.',teamMode()?rivalButtons('applyRed'):playerButtons('applyRed',[S.current],false),'Si tiene ESCUDO, lo consume automáticamente y bloquea la Roja.','CASTIGO')}
function applyRed(i){playFx('red');vibrate([70,35,70]);let p=S.players[i];if(S.turnCtx)S.turnCtx.powerStage='POST_DONE';if(p.powers.includes('ESCUDO')){p.powers=p.powers.filter(x=>x!=='ESCUDO');save();return showPower('🛡️','ESCUDO',`${p.name} bloqueó la Roja y consumió su Escudo.`,[`<button class="btn btn-primary" onclick="nextTurn()">SIGUIENTE TURNO</button>`],'El Escudo queda gastado.','DEFENSA')};p.redTurns=1;save();showPower('🟥','ROJA APLICADA',`${p.name} jugará su próximo turno sin poderes especiales.`,[`<button class="btn btn-primary" onclick="nextTurn()">SIGUIENTE TURNO</button>`],'La sanción se limpia al terminar ese turno.','CASTIGO')}
function chooseMiniRival(type){let title=type==='FINAL'?'LA FINAL':'PENALES';let icon=type==='FINAL'?'🏆':'⚽';let text=type==='FINAL'?'Elegí a un rival para disputar la Final especial.':'Elegí a un rival para la definición por penales.';showPower(icon,title,text,teamMode()?rivalButtons(type==='FINAL'?'startFinalVs':'startPenaltiesVs'):playerButtons(type==='FINAL'?'startFinalVs':'startPenaltiesVs',[S.current],false),type==='FINAL'?'Tres penales por lado. Si empatan, muerte súbita en LEYENDA. El ganador obtiene +2 o un Escudo.':'Tres penales por lado. Si empatan, muerte súbita en LEYENDA.','MINIJUEGO')}
function startPenaltiesVs(i){beginShootout('PENALES',i)}
function startFinalVs(i){beginShootout('FINAL',i)}
function beginShootout(type,rival,ownerOverride=null){let owner=ownerOverride==null?S.current:ownerOverride;if(S.turnCtx)S.turnCtx.powerStage=null;S.shootout={type,owner,rival,kicksA:[],kicksB:[],side:'A',sudden:false,currentPen:null};prepareShootoutKick();save();go('shootout')}
function pickPenalty(diff){let d=diff||effectiveDifficulty();let pool=DB.penalties.filter(x=>x.difficulty===d&&!S.usedPen.includes(x.id));if(!pool.length)pool=DB.penalties.filter(x=>x.difficulty===d);let q=pool[Math.floor(Math.random()*pool.length)];if(q)S.usedPen.push(q.id);return q}
function prepareShootoutKick(){let sh=S.shootout;if(!sh)return;let diff=sh.sudden?'LEYENDA':(S.currentContent?.difficulty||effectiveDifficulty());sh.currentPen=pickPenalty(diff);document.getElementById('shootReady').classList.remove('hidden');document.getElementById('shootContent').classList.add('hidden');document.getElementById('shootAnswer').classList.add('hidden');document.getElementById('shootActions').classList.add('hidden');save()}
function kickMarks(a){return a.map(x=>x?'⚽':'🧤').join(' ')||'—'}
function renderShootout(){let sh=S.shootout;if(!sh)return;document.getElementById('shootBrand').textContent=sh.type==='FINAL'?'🏆 LA FINAL':(sh.type==='TIEBREAK'||sh.type==='TEAM_TIEBREAK')?'⚖️ DESEMPATE':'⚽ PENALES';document.getElementById('shootMode').textContent=sh.sudden?'MUERTE SÚBITA':'3 PENALES POR LADO';document.getElementById('shootTitle').textContent=sh.type==='FINAL'?'FINAL ESPECIAL':(sh.type==='TIEBREAK'||sh.type==='TEAM_TIEBREAK')?'DESEMPATE DEL PARTIDO':'DEFINICIÓN POR PENALES';document.getElementById('shootSubtitle').textContent=sh.sudden?'Ahora todas las preguntas son LEYENDA.':'Si siguen empatados después de tres por lado, pasan a muerte súbita.';document.getElementById('shootNameA').textContent=S.players[sh.owner].name;document.getElementById('shootNameB').textContent=S.players[sh.rival].name;document.getElementById('shootKicksA').textContent=kickMarks(sh.kicksA);document.getElementById('shootKicksB').textContent=kickMarks(sh.kicksB);let shooter=sh.side==='A'?sh.owner:sh.rival;document.getElementById('shootShooter').textContent='PATEA · '+S.players[shooter].name}
function startShootoutKick(){let sh=S.shootout;if(!sh||!sh.currentPen)return;playFx('whistle');document.getElementById('shootReady').classList.add('hidden');document.getElementById('shootContent').classList.remove('hidden');document.getElementById('shootQuestion').textContent=sh.currentPen.question;let t=5,el=document.getElementById('shootTimer');el.textContent=t;clearInterval(shootInt);shootInt=setInterval(()=>{t--;el.textContent=t;if(t<=3&&t>0)playFx('tick');if(t<=0){clearInterval(shootInt);el.textContent='0';vibrate([45])}},1000)}
function showShootoutAnswer(){clearInterval(shootInt);let sh=S.shootout;document.getElementById('shootAnswer').textContent=sh.currentPen.answer;document.getElementById('shootAnswer').classList.remove('hidden');document.getElementById('shootActions').classList.remove('hidden')}
function shootScore(arr){return arr.filter(Boolean).length}
function finishShootoutKick(ok){let sh=S.shootout;if(sh.side==='A')sh.kicksA.push(ok);else sh.kicksB.push(ok);if(sh.side==='A'){sh.side='B';prepareShootoutKick();renderShootout();return go('shootout')}let paired=sh.kicksA.length===sh.kicksB.length;if(paired&&sh.kicksA.length>=3){let a=shootScore(sh.kicksA),b=shootScore(sh.kicksB);if(a!==b)return finishShootout(a>b?sh.owner:sh.rival);sh.sudden=true}sh.side='A';prepareShootoutKick();renderShootout();go('shootout')}
function finishShootout(winner){let sh=S.shootout,loser=winner===sh.owner?sh.rival:sh.owner;if(sh.type==='TEAM_TIEBREAK'){let team=S.players[winner].team;S.shootout=null;save();return finishTeamGame(team,'Desempate definido por penales.')}if(sh.type==='TIEBREAK'){let scoreA=shootScore(sh.kicksA),scoreB=shootScore(sh.kicksB);let remaining=Array.isArray(S.tiebreakQueue)?S.tiebreakQueue.filter(i=>i!==sh.owner&&i!==sh.rival):[];if(remaining.length){let next=remaining.shift();S.tiebreakQueue=[winner,...remaining];S.shootout=null;save();return beginShootout('TIEBREAK',next,winner)}S.shootout=null;S.tiebreakQueue=[];save();return finishGame(S.players[winner])}
if(sh.type==='FINAL'){if(pointsMode())addPoints(winner,2);else if(!S.players[winner].powers.includes('ESCUDO'))S.players[winner].powers.push('ESCUDO')}else{if(pointsMode())addPoints(winner,1);else if(!S.players[winner].powers.includes('ESCUDO'))S.players[winner].powers.push('ESCUDO')}playFx(sh.type==='FINAL'?'win':'goal');document.getElementById('resultIcon').textContent=sh.type==='FINAL'?'🏆':'⚽';document.getElementById('resultTitle').textContent=sh.type==='FINAL'?'FINAL GANADA':'PENALES GANADOS';document.getElementById('resultText').textContent=`${S.players[winner].name} ganó ${shootScore(sh.kicksA)}–${shootScore(sh.kicksB)} ante ${S.players[loser].name}.`;S.shootout=null;save();go('result')}
function alivePlayers(){return S.players.map((p,i)=>({p,i})).filter(x=>x.p.lives>0)}
function nextTeamPlayer(){let curTeam=S.players[S.current]?.team===1?1:0,target=curTeam===0?1:0,indices=S.players.map((p,i)=>({p,i})).filter(x=>x.p.team===target).map(x=>x.i);if(!indices.length){S.current=(S.current+1)%S.players.length;return}let pos=(S.teamCursors[target]||0)%indices.length;S.current=indices[pos];S.teamCursors[target]=(pos+1)%indices.length}
function nextTurn(){let ending=S.current;if(S.players[ending]?.redTurns>0)S.players[ending].redTurns=Math.max(0,S.players[ending].redTurns-1);if(S.mode==='ELIMINACION'){let alive=alivePlayers();if(alive.length<=1)return finishGame(alive[0]?.p||S.players[0]);let tries=0;do{S.current=(S.current+1)%S.players.length;tries++}while(S.players[S.current].lives<=0&&tries<=S.players.length)}else if(teamMode())nextTeamPlayer();else S.current=(S.current+1)%S.players.length;if(S.mode==='FINAL'&&S.turnCount>=12)return endGameByScore();if(S.playFormat==='DIGITAL'&&S.mode==='PUNTOS'&&Math.max(...S.players.map(p=>p.score))>=10)return endGameByScore();if(S.playFormat==='DIGITAL'&&teamMode()&&Math.max(...S.teams.map(t=>t.score))>=10)return endTeamGameByScore();S.turnCtx=null;S.lastOutcome=null;S.currentContent=null;S.currentBlock=null;save();go('turn')}
