function playRepeatedOriginal(){if(S.turnCtx)S.turnCtx.powerStage=null;enterCurrentContent()}
function playRepeatedVariant(){let base=S.currentContent;let options=DB.content.filter(x=>x.difficulty===base.difficulty&&x.category===base.category&&x.id!==base.id&&!S.used.includes(x.id));if(!options.length)options=DB.content.filter(x=>x.difficulty===base.difficulty&&x.category===base.category&&x.id!==base.id);if(!options.length)return playRepeatedOriginal();let alt={...options[Math.floor(Math.random()*options.length)]};S.used.push(alt.id);S.currentContent={...alt,block:S.currentBlock,event:base.event,variantOf:alt.id};S.turnCtx.event=base.event;S.turnCtx.eventHandled=false;S.turnCtx.eventDisabled=false;S.turnCtx.repeated=false;S.turnCtx.repeatHandled=true;S.turnCtx.diceResolved=base.event!=='DADO';S.turnCtx.powerStage=null;save();enterCurrentContent()}
function continueToChallenge(){renderChallenge();save();go('challenge')}
function setCaptainHelper(i){S.turnCtx.helper=i;showPower('⭐','CAPITÁN ACTIVADO',`${S.players[i].name} puede ayudar a ${S.players[S.current].name}.`,[`<button class="btn btn-primary" onclick="continueToChallenge()">VER CONSIGNA</button>`],'Una sola ayuda durante esta jugada.','PODER ACTIVO')}
function activateHinchada(){S.turnCtx.hinchada=true;continueToChallenge()}
function setContraTarget(i){S.turnCtx.responder=i;S.turnCtx.contra=true;showPower('⚡','CONTRAATAQUE',`${S.players[i].name} deberá responder esta consigna.`,[`<button class="btn btn-primary" onclick="continueToChallenge()">LANZAR CONTRAATAQUE</button>`],teamMode()?'Si acierta, suma para su equipo. Si falla, tu equipo obtiene +1.':'Si acierta, suma para él/ella. Si falla, recibe el fallo y vos obtenés +1 en modos con puntos.','RIVAL BAJO PRESIÓN')}
function setEl10Responder(i){S.turnCtx.responder=i;S.turnCtx.el10=true;showPower('🔟','EL 10',`${S.players[i].name} responderá por ${S.players[S.current].name}.`,[`<button class="btn btn-primary" onclick="continueToChallenge()">DARLE LA PELOTA</button>`],'El acierto o fallo cuenta para el dueño del turno.','JUGADA DE CRACK')}
function renderChallenge(){let c=S.currentContent;if(!c)return;renderHud('challengeHud');document.getElementById('catLabel').textContent=`${catIcons[c.category]||''} ${c.category.replace('_',' ')} · BLOQUE ${String(c.block).padStart(2,'0')} · ${c.difficulty}`;document.getElementById('questionText').textContent=c.question;let e=document.getElementById('eventBox');let ctx=S.turnCtx||{};let notes=[];if(c.event)notes.push((ctx.eventDisabled?'ANULADO · ':'EVENTO · ')+c.event.replace('_',' '));if(ctx.helper!=null)notes.push('⭐ Ayuda: '+S.players[ctx.helper].name);if(ctx.hinchada)notes.push('📣 Hinchada habilitada');if(ctx.contra)notes.push('⚡ Responde: '+S.players[ctx.responder].name);if(ctx.el10&&ctx.responder!==ctx.owner)notes.push('🔟 Responde por vos: '+S.players[ctx.responder].name);if(ctx.rematchUsed)notes.push('🔁 Segunda oportunidad');if(notes.length){e.classList.remove('hidden');e.textContent=notes.join(' · ')}else e.classList.add('hidden');document.getElementById('diceBtn').style.display=c.event==='DADO'&&!ctx.diceResolved?'block':'none';let rb=document.getElementById('revealBtn');if(rb){rb.disabled=c.event==='DADO'&&!ctx.diceResolved;rb.textContent=c.event==='DADO'&&!ctx.diceResolved?'PRIMERO RESOLVÉ EL DADO':'MOSTRAR RESPUESTA'}let tw=document.getElementById('timerWrap');if(c.timer>0){tw.classList.remove('hidden');document.getElementById('timer').textContent=c.timer;document.getElementById('timer').className='timer'}else tw.classList.add('hidden')}
function startTimer(){clearInterval(timerHandle);let t=S.currentContent.timer,el=document.getElementById('timer');el.textContent=t;el.className='timer';timerHandle=setInterval(()=>{t--;el.textContent=t;el.className='timer'+(t<=5?' low':'');if(t<=3&&t>0)playFx('tick');if(t<=0){clearInterval(timerHandle);el.textContent='0';el.className='timer zero';vibrate([45])}},1000)}
function revealAnswer(){if(S.currentContent?.event==='DADO'&&!S.turnCtx?.diceResolved)return showDice();clearInterval(timerHandle);document.getElementById('answerMeta').textContent=`${S.currentContent.category.replace('_',' ')} · ${S.currentContent.difficulty}`;document.getElementById('answerText').textContent=S.currentContent.answer;go('answer')}
function scoreValue(){return S.currentContent&&S.currentContent.difficulty==='LEYENDA'?2:1}
function chooseAlternateContent(){let c=S.currentContent;let options=DB.content.filter(x=>x.difficulty===c.difficulty&&x.category===c.category&&x.id!==c.id&&!S.used.includes(x.id));if(!options.length)options=DB.content.filter(x=>x.difficulty===c.difficulty&&x.category===c.category&&x.id!==c.id);if(!options.length)return null;let alt={...options[Math.floor(Math.random()*options.length)]};alt.event=null;S.used.push(alt.id);return alt}
function offerSecondChance(source){if(S.turnCtx){S.turnCtx.powerStage='SECOND_CHANCE';S.turnCtx.secondChanceSource=source;}let title=source==='REMONTADA'?'REMONTADA':source==='COPA'?'LA COPA':'REPLAY';let icon=source==='REMONTADA'?'⭐':source==='COPA'?'🏆':'🔁';let rule=source==='COPA'?'Se consume al usarla.':'La nueva consigna será de la misma categoría y dificultad.';showPower(icon,title,'Fallaste, pero todavía podés salvar la jugada.',[`<button class="btn btn-primary" onclick="useSecondChance('${source}')">USAR SEGUNDA OPORTUNIDAD</button>`,`<button class="btn btn-ghost" onclick="finalizeResolution(false)">ACEPTAR EL FALLO</button>`],rule,'SEGUNDA OPORTUNIDAD')}
function useSecondChance(source){let alt=chooseAlternateContent();if(!alt)return finalizeResolution(false);if(source==='COPA'){let p=S.players[S.turnCtx.owner];p.powers=p.powers.filter(x=>x!=='COPA')}S.turnCtx.rematchUsed=true;S.turnCtx.powerStage=null;S.turnCtx.secondChanceSource=null;S.turnCtx.copaJustEarned=false;if(source==='REMONTADA')S.turnCtx.remontadaUsed=true;if(source==='REPLAY')S.turnCtx.diceReplay=false;S.currentContent=alt;save();continueToChallenge()}
function resolve(ok){let ctx=S.turnCtx||{owner:S.current,responder:S.current,event:null};if(!ok&&!ctx.rematchUsed){if(ctx.diceReplay)return offerSecondChance('REPLAY');if(!ctx.redActive){if(ctx.event==='REMONTADA'&&!ctx.remontadaUsed)return offerSecondChance('REMONTADA');let owner=S.players[ctx.owner];if(owner.powers.includes('COPA')&&!ctx.copaJustEarned)return offerSecondChance('COPA')}}finalizeResolution(ok)}
function finalizeResolution(ok){let ctx=S.turnCtx||{owner:S.current,responder:S.current};if(S.lastOutcome)return;ctx.powerStage=null;let subject=ctx.contra?ctx.responder:ctx.owner;let p=S.players[subject];let pts=scoreValue();if(pointsMode()&&ok)addPoints(subject,pts);if(S.mode==='ELIMINACION'&&!ok)p.lives=Math.max(0,p.lives-1);if(ctx.contra&&!ok&&pointsMode())addPoints(ctx.owner,1);S.turnCount++;S.lastOutcome={ok,subject,owner:ctx.owner,contra:!!ctx.contra};document.getElementById('resultIcon').textContent=ok?'⚽':'🧤';document.getElementById('resultTitle').textContent=ok?'¡GOOOL!':'ATAJADA';let who=subject!==ctx.owner?S.players[subject].name+' ':' ';let teamTxt=teamMode()?` ${teamName(S.players[subject].team)} queda ${S.teams[S.players[subject].team].score} pts.`:'';document.getElementById('resultText').textContent=ok?(who+'superó la jugada'+(S.currentContent.difficulty==='LEYENDA'&&S.mode!=='ELIMINACION'?' y vale doble.':'.')+teamTxt):(who+'no pudo resolverla.'+(ctx.contra&&pointsMode()?' Contraataque: +1 para '+S.players[ctx.owner].name+'.':''));playFx(ok?'goal':'save');vibrate(ok?[35,25,50]:[80]);save();go('result')}
