let DB=null;
const formats=[
 ['FISICA','🧱','Con Torre Física','Usá la torre real, sacá una pieza e ingresá su número.','HÍBRIDO'],
 ['DIGITAL','📱','Solo Digital','El portal sortea el bloque. No necesitás ningún elemento físico.','100% DIGITAL']
];
const modesPhysical=[['CLASICO','🏗️','Clásico','La torre manda. La partida termina cuando cae.'],['PUNTOS','🏆','Puntos','Cada acierto suma. La torre decide cuándo termina.'],['EQUIPOS','👥','Equipos','Dos equipos. Cada acierto suma; si cae la torre pierde el equipo que la derriba.'],['ELIMINACION','❤️','Eliminación','Tres vidas por jugador.'],['FINAL','⚡','Final rápida','12 jugadas y gana el mejor puntaje.']];
const modesDigital=[['PUNTOS','🏆','Puntos','Primero en llegar a 10 puntos.'],['EQUIPOS','👥','Equipos','Dos equipos. Primero en llegar a 10 puntos.'],['ELIMINACION','❤️','Eliminación','Tres vidas. El último con vida gana.'],['FINAL','⚡','Final rápida','12 jugadas digitales y gana el mejor puntaje.']];
const diffs=[['FACIL','⚽','FÁCIL','Para disfrutar y entrar en calor'],['MEDIO','⚽⚽','MEDIO','Para los que siguen fútbol en serio'],['LEYENDA','⚽⚽⚽','LEYENDA','Historia profunda, pero jugable'],['MIXTO','🔀','MIXTO','La dificultad cambia en cada turno']];
const catIcons={TRIVIA:'🧠',QUIEN_SOY:'🕵️',HISTORIA:'📜',DESAFIO:'🎯',DUELO:'⚔️',LOCURA:'🔥'};
let S={playFormat:'FISICA',mode:'PUNTOS',difficulty:'MEDIO',teams:[{name:'Equipo A',score:0},{name:'Equipo B',score:0}],teamCursors:[0,0],settings:{audio:true,vibration:true,animations:true},players:[{name:'Gas',score:0,lives:3,powers:[],redTurns:0,team:0},{name:'Jugador 2',score:0,lives:3,powers:[],redTurns:0,team:1}],current:0,used:[],usedPen:[],recentBlocks:[],currentContent:null,currentBlock:null,dice:null,started:false,turnCount:0,turnCtx:null,lastOutcome:null,shootout:null,tiebreakQueue:[],activePenalty:null};
let timerHandle=null,pen=null,penInt=null,shootInt=null,powerReturn='challenge',penOrigin='DICE';

function normPlayer(p,i){return {name:(p&&p.name)||('Jugador '+(i+1)),score:Number(p?.score||0),lives:Number.isFinite(p?.lives)?p.lives:3,powers:Array.isArray(p?.powers)?p.powers:[],redTurns:Number(p?.redTurns||0),team:(p?.team===1?1:0)}}
function normalizeState(){S.players=(S.players||[]).map(normPlayer);if(!S.players.length)S.players=[normPlayer({name:'Jugador 1',team:0},0),normPlayer({name:'Jugador 2',team:1},1)];if(!Array.isArray(S.teams)||S.teams.length<2)S.teams=[{name:'Equipo A',score:0},{name:'Equipo B',score:0}];S.teams=S.teams.slice(0,2).map((t,i)=>({name:(t?.name||('Equipo '+(i?'B':'A'))),score:Number(t?.score||0)}));if(!Array.isArray(S.teamCursors)||S.teamCursors.length<2)S.teamCursors=[0,0];if(!S.settings)S.settings={audio:true,vibration:true,animations:true};S.settings={audio:S.settings.audio!==false,vibration:S.settings.vibration!==false,animations:S.settings.animations!==false};if(!Array.isArray(S.used))S.used=[];if(!Array.isArray(S.usedPen))S.usedPen=[];if(!Array.isArray(S.recentBlocks))S.recentBlocks=[];if(typeof S.turnCount!=='number')S.turnCount=0;if(!('turnCtx' in S))S.turnCtx=null;if(!('lastOutcome' in S))S.lastOutcome=null;if(!('shootout' in S))S.shootout=null;if(!Array.isArray(S.tiebreakQueue))S.tiebreakQueue=[];if(!('activePenalty' in S))S.activePenalty=null;applyFxSetting()}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));let el=document.getElementById(id);if(el)el.classList.add('active');if(id==='summary')renderSummary();if(id==='turn')renderTurn();if(id==='scores')renderScores();if(id==='format')renderFormats();if(id==='mode')renderModes();if(id==='players')renderPlayers();if(id==='difficulty')renderDiffs();if(id==='shootout')renderShootout();if(id==='settings')renderSettings();updateResumeButton();window.scrollTo(0,0)}
function goHome(){if(S.started)save();go('home')}
function updateResumeButton(){let b=document.getElementById('resumeBtn');if(b)b.style.display=localStorage.getItem('torreAmericaGame')?'block':'none'}
function renderFormats(){document.getElementById('formatOpts').innerHTML=formats.map(x=>`<div class="format-card ${S.playFormat===x[0]?'selected':''}" onclick="S.playFormat='${x[0]}';renderFormats()"><div class="format-ribbon">${x[4]}</div><div class="format-icon">${x[1]}</div><h3>${x[2]}</h3><p>${x[3]}</p></div>`).join('')}
function ensureModeForFormat(){if(S.playFormat==='DIGITAL'&&S.mode==='CLASICO')S.mode='PUNTOS'}
function renderModes(){ensureModeForFormat();let items=S.playFormat==='DIGITAL'?modesDigital:modesPhysical;document.getElementById('modeOpts').innerHTML=items.map(x=>`<div class="option ${S.mode===x[0]?'selected':''}" onclick="S.mode='${x[0]}';renderModes()"><div class="option-icon">${x[1]}</div><div><strong>${x[2]}</strong><small>${x[3]}</small></div><div class="check">${S.mode===x[0]?'✓':''}</div></div>`).join('')}
