function showDice(){go('dice')}
function randomDice(){let a=['GOL','ATAJADA','VAR','REPLAY','FALTA','PENAL'];diceResult(a[Math.floor(Math.random()*a.length)])}
function showDiceOutcome(icon,title,text){showPower(icon,title,text,[`<button class="btn btn-primary" onclick="continueToChallenge()">CONTINUAR CONSIGNA</button>`],'El dado modifica esta jugada.','RESULTADO DEL DADO')}
function diceResult(r){if(S.turnCtx?.diceResolved)return;playFx('dice');vibrate([25]);S.dice=r;if(S.turnCtx)S.turnCtx.diceResolved=true;let p=S.players[S.current];if(r==='PENAL'){save();penOrigin='DICE';return openPenalty()}if(r==='VAR'){let alt=chooseAlternateContent();if(alt){let originalBlock=S.currentBlock;S.currentContent={...alt,block:originalBlock,event:'DADO',variantOf:alt.id}}save();return showDiceOutcome('📺','VAR','La consigna fue reemplazada por otra de la misma categoría y dificultad.')}if(r==='REPLAY'){S.turnCtx.diceReplay=true;save();return showDiceOutcome('🔁','REPLAY','Si fallás esta consigna vas a tener una segunda oportunidad, incluso si estás bajo Roja.')}if(r==='FALTA'){if(p.powers.includes('ESCUDO')){p.powers=p.powers.filter(x=>x!=='ESCUDO');save();return showDiceOutcome('🛡️','ESCUDO','Tu Escudo bloqueó la Falta y fue consumido.')}if(S.currentContent.timer===0){S.currentContent={...S.currentContent,timer:20};save();return showDiceOutcome('🟥','FALTA','La consigna era libre: ahora tenés 20 segundos para resolverla.')}if(S.currentContent.timer>5)S.currentContent={...S.currentContent,timer:Math.max(5,S.currentContent.timer-5)};save();return showDiceOutcome('🟥','FALTA','Tu tiempo fue reducido 5 segundos. Nunca baja de 5.')}if(r==='GOL'){playFx('goal');if(pointsMode())addPoints(S.current,1);else if(!p.powers.includes('ESCUDO'))p.powers.push('ESCUDO');save();return showDiceOutcome('⚽','GOL',pointsMode()?'+1 punto inmediato.':'Ganaste un ESCUDO para proteger una jugada futura.')}if(r==='ATAJADA'){if(!p.powers.includes('ESCUDO'))p.powers.push('ESCUDO');save();return showDiceOutcome('🧤','ATAJADA','Ganaste un ESCUDO para bloquear un efecto negativo futuro.')}save();continueToChallenge()}
function openPenalty(){let d=S.currentContent?.difficulty||effectiveDifficulty();let pool=DB.penalties.filter(x=>x.difficulty===d&&!S.usedPen.includes(x.id));if(!pool.length)pool=DB.penalties.filter(x=>x.difficulty===d);pen=pool[Math.floor(Math.random()*pool.length)];S.activePenalty={...pen,origin:penOrigin};S.usedPen.push(pen.id);document.getElementById('penPlayer').textContent='Patea '+S.players[S.current].name;document.getElementById('penReady').classList.remove('hidden');document.getElementById('penContent').classList.add('hidden');document.getElementById('penAnswer').classList.add('hidden');document.getElementById('penActions').classList.add('hidden');save();go('penalty')}
function startPenalty(){playFx('whistle');document.getElementById('penReady').classList.add('hidden');document.getElementById('penContent').classList.remove('hidden');document.getElementById('penQuestion').textContent=pen.question;let t=5,el=document.getElementById('penTimer');el.textContent=t;clearInterval(penInt);penInt=setInterval(()=>{t--;el.textContent=t;if(t<=3&&t>0)playFx('tick');if(t<=0){clearInterval(penInt);el.textContent='0';vibrate([45])}},1000)}
function showPenaltyAnswer(){clearInterval(penInt);document.getElementById('penAnswer').textContent=pen.answer;document.getElementById('penAnswer').classList.remove('hidden');document.getElementById('penActions').classList.remove('hidden')}
function finishPenalty(ok){let q=pen||S.activePenalty;if(!q)return;if(pointsMode()&&ok)addPoints(S.current,1);if(S.mode==='ELIMINACION'&&!ok)S.players[S.current].lives=Math.max(0,S.players[S.current].lives-1);playFx(ok?'goal':'save');vibrate(ok?[30,25,45]:[70]);S.activePenalty=null;save();if(penOrigin==='DICE'){if(S.turnCtx)S.turnCtx.powerStage='DICE_OUTCOME';return showPower(ok?'⚽':'🧤',ok?'PENAL CONVERTIDO':'PENAL ATAJADO',`${q.question} → ${q.answer}`,[`<button class="btn btn-primary" onclick="continueToChallenge()">CONTINUAR CONSIGNA</button>`],ok?(pointsMode()?'El penal suma +1.':'Penal convertido.'):(S.mode==='ELIMINACION'?'Fallaste el penal: -1 vida.':'La jugada principal todavía continúa.'),'PENAL DEL DADO')}document.getElementById('resultIcon').textContent=ok?'⚽':'🧤';document.getElementById('resultTitle').textContent=ok?'PENAL CONVERTIDO':'PENAL ATAJADO';document.getElementById('resultText').textContent=q.question+' → '+q.answer;go('result')}
function forfeitPenalty(){if(!S.activePenalty&&!pen)return continueToChallenge();finishPenalty(false)}
function renderScores(){let teams=teamMode()?`<div class="team-scoreboard"><div class="team-score a"><b>${teamName(0)}</b><strong>${S.teams[0].score}</strong></div><div class="team-vs">VS</div><div class="team-score b"><b>${teamName(1)}</b><strong>${S.teams[1].score}</strong></div></div>`:'';document.getElementById('scoreBox').innerHTML=teams+S.players.map((p,i)=>`<div class="score-row"><span class="score-name">${i===S.current?'▶ ':''}${escapeHtml(p.name)} ${teamMode()?`<span class="mini">· ${teamName(p.team)}</span>`:''} ${powerIcons(p)}</span><span class="score-value">${p.score} pts · ${p.lives} ❤️</span></div>`).join('')}
function showScores(){renderScores();go('scores')}
function winnerByScore(){return [...S.players].sort((a,b)=>b.score-a.score||b.lives-a.lives)[0]}
function topScoreIndices(){let max=Math.max(...S.players.map(p=>p.score));return S.players.map((p,i)=>({p,i})).filter(x=>x.p.score===max).map(x=>x.i)}
function startScoreTiebreak(indices){if(indices.length<2)return finishGame(S.players[indices[0]??0]);S.tiebreakQueue=[...indices];let owner=S.tiebreakQueue.shift(),rival=S.tiebreakQueue.shift();S.tiebreakQueue=[owner,rival,...S.tiebreakQueue];beginShootout('TIEBREAK',rival,owner)}
function towerFell(){if(teamMode()){let loser=S.players[S.current].team,winner=loser===0?1:0;return finishTeamGame(winner,'La torre cayó: pierde '+teamName(loser)+'.')}let win;if(S.mode==='PUNTOS'||S.mode==='FINAL'){let tied=topScoreIndices();if(tied.length>1)return startScoreTiebreak(tied);win=S.players[tied[0]]}else if(S.mode==='CLASICO'){let prev=(S.current-1+S.players.length)%S.players.length;win=S.players[prev]}else{let survivors=S.players.map((p,i)=>({p,i})).filter(x=>x.i!==S.current&&x.p.lives>0);survivors.sort((a,b)=>b.p.lives-a.p.lives);win=survivors[0]?.p||S.players[(S.current-1+S.players.length)%S.players.length]}finishGame(win)}
function endGameByScore(){if(teamMode())return endTeamGameByScore();let tied=topScoreIndices();if(tied.length>1)return startScoreTiebreak(tied);finishGame(S.players[tied[0]])}
function endTeamGameByScore(){let lead=teamLeader();if(lead<0){let a=S.players.findIndex(p=>p.team===0),b=S.players.findIndex(p=>p.team===1);return beginShootout('TEAM_TIEBREAK',b,a)}finishTeamGame(lead)}
function finishTeamGame(teamIdx,reason=''){let t=S.teams[teamIdx];document.getElementById('winnerEyebrow').textContent='EQUIPO CAMPEÓN';document.getElementById('winnerName').textContent=t.name;document.getElementById('winnerCopy').textContent=reason||'La copa es de todo el equipo.';document.getElementById('finalScores').innerHTML=`<div class="team-scoreboard"><div class="team-score a"><b>${teamName(0)}</b><strong>${S.teams[0].score}</strong></div><div class="team-vs">VS</div><div class="team-score b"><b>${teamName(1)}</b><strong>${S.teams[1].score}</strong></div></div>`+S.players.map(p=>`<div class="score-row"><span>${escapeHtml(p.name)} · ${teamName(p.team)}</span><b>${p.score} pts</b></div>`).join('');playFx('win');vibrate([80,40,80,40,150]);S.started=false;S.activePenalty=null;localStorage.removeItem('torreAmericaGame');go('gameover')}
function finishGame(win){document.getElementById('winnerEyebrow').textContent='CAMPEÓN DE LA NOCHE';document.getElementById('winnerCopy').textContent='La copa ya tiene dueño.';document.getElementById('winnerName').textContent=win.name;let ordered=[...S.players].sort((a,b)=>b.score-a.score||(a===win?-1:b===win?1:0)||b.lives-a.lives);document.getElementById('finalScores').innerHTML=ordered.map(p=>`<div class="score-row"><span class="score-name">${p===win?'🏆 ':''}${escapeHtml(p.name)} ${powerIcons(p)}</span><span class="score-value">${p.score} pts · ${p.lives} ❤️</span></div>`).join('');playFx('win');vibrate([80,40,80,40,150]);S.started=false;S.activePenalty=null;localStorage.removeItem('torreAmericaGame');go('gameover')}
function rematch(){S.started=false;startGame()}
function newGame(){localStorage.removeItem('torreAmericaGame');S.started=false;S.current=0;S.turnCount=0;S.turnCtx=null;S.shootout=null;S.tiebreakQueue=[];S.activePenalty=null;go('format')}
