function powerIcons(p){let a=[];if(p.powers.includes('COPA'))a.push('🏆');if(p.powers.includes('ESCUDO'))a.push('🛡️');if(p.redTurns>0)a.push('🟥');return a.join(' ')}
function renderHud(target='hud'){let p=S.players[S.current];let status=S.mode==='ELIMINACION'?`❤️ ${p.lives}`:teamMode()?`👥 ${teamName(p.team)} · ${S.teams[p.team].score}`:`⭐ ${p.score}`;let extra=powerIcons(p);document.getElementById(target).innerHTML=`<span class="pill gold">${escapeHtml(p.name)}</span><span class="pill">${formatLabel()}</span><span class="pill">${S.difficulty}</span><span class="pill">${status}</span>${extra?`<span class="pill red">${extra}</span>`:''}`}
function renderTurn(){if(!S.started)return;normalizeState();let p=S.players[S.current];document.getElementById('turnName').textContent=p.name;renderHud('hud');let ins=document.getElementById('turnInstruction'),ico=document.getElementById('turnIcon'),act=document.getElementById('turnActions');let team=teamMode()?` · ${teamName(p.team)} (${S.teams[p.team].score} pts)`:'';let red=p.redTurns>0?' 🟥 Estás con Roja: este turno no podés usar poderes especiales.':'';if(S.playFormat==='FISICA'){ins.textContent='Sacá un bloque de la torre y mirá su número.'+team+red;ico.textContent=p.redTurns>0?'🟥🧱':'🧱';act.innerHTML=`<button class="btn btn-primary" onclick="go('blocks')">YA LO TENGO</button><button class="btn btn-danger" onclick="towerFell()">💥 LA TORRE CAYÓ</button>`}else{ins.textContent='El portal va a sortear tu bloque 01–54.'+team+red;ico.textContent=p.redTurns>0?'🟥📱':'📱⚽';act.innerHTML=`<button class="btn btn-primary" onclick="drawDigitalBlock()">SACAR BLOQUE DIGITAL</button><button class="btn btn-secondary" onclick="showScores()">VER MARCADOR</button>`}}
let bg=document.getElementById('blockGrid');bg.innerHTML=Array.from({length:54},(_,i)=>`<button class="block" onclick="selectPhysicalBlock(${i+1})">${String(i+1).padStart(2,'0')}</button>`).join('');
function effectiveDifficulty(){if(S.difficulty!=='MIXTO')return S.difficulty;let r=Math.random();return r<.30?'FACIL':r<.75?'MEDIO':'LEYENDA'}
function prepareContent(n){let d=effectiveDifficulty();let c=DB.content.find(x=>x.block===n&&x.difficulty===d);if(!c)return false;let wasUsed=S.used.includes(c.id);S.currentBlock=n;S.currentContent={...c};if(!wasUsed)S.used.push(c.id);S.recentBlocks.push(n);if(S.recentBlocks.length>8)S.recentBlocks.shift();S.turnCtx={owner:S.current,responder:S.current,event:c.event,eventHandled:false,eventDisabled:false,helper:null,hinchada:false,contra:false,el10:false,rematchUsed:false,diceReplay:false,diceResolved:c.event!=='DADO',postDone:false,redActive:S.players[S.current].redTurns>0,repeated:wasUsed,repeatHandled:!wasUsed,copaJustEarned:false,powerStage:null};S.lastOutcome=null;save();return true}
function selectPhysicalBlock(n){if(prepareContent(n))enterCurrentContent()}
function drawDigitalBlock(){let pool=Array.from({length:54},(_,i)=>i+1).filter(n=>!S.recentBlocks.includes(n));if(!pool.length)pool=Array.from({length:54},(_,i)=>i+1);let n=pool[Math.floor(Math.random()*pool.length)];if(!prepareContent(n))return;document.getElementById('digitalBlockNumber').textContent=String(n).padStart(2,'0');document.getElementById('digitalBlockMeta').textContent=`${catIcons[S.currentContent.category]||''} ${S.currentContent.category.replace('_',' ')} · ${S.currentContent.difficulty}`;go('digitalblock')}
function backFromChallenge(){go(S.playFormat==='FISICA'?'blocks':'digitalblock')}
function powerBack(){let ctx=S.turnCtx||{};if(ctx.powerStage==='SECOND_CHANCE')return finalizeResolution(false);if(ctx.powerStage==='POST_RED')return chooseRedTarget();if(ctx.powerStage==='POST_PENALES')return chooseMiniRival('PENALES');if(ctx.powerStage==='POST_FINAL')return chooseMiniRival('FINAL');if(ctx.powerStage==='POST_DONE')return nextTurn();if(ctx.powerStage==='PRE_CONTRA'){ctx.eventHandled=true;return showPower('⚡','CONTRAATAQUE','Elegí un rival para enviarle esta consigna.',teamMode()?rivalButtons('setContraTarget'):playerButtons('setContraTarget',[S.current],false),'Este poder forma parte del bloque y debe resolverse.','RIVAL BAJO PRESIÓN')}if(ctx.powerStage==='PRE_EL10'){ctx.eventHandled=true;return showPower('🔟','EL 10','Elegí quién responderá por vos.',teamMode()?mateButtons('setEl10Responder',true):playerButtons('setEl10Responder',[],true),'Podés elegirte a vos mismo.','JUGADA DE CRACK')}if(S.started&&S.currentContent){renderChallenge();go('challenge')}else go('turn')}
function showPower(icon,title,text,buttons,rule='',eyebrow='PODER ESPECIAL'){playFx(title==='ROJA'?'red':'power');document.getElementById('powerIcon').textContent=icon;document.getElementById('powerTitle').textContent=title;document.getElementById('powerText').textContent=text;document.getElementById('powerEyebrow').textContent=eyebrow;let r=document.getElementById('powerRule');if(rule){r.textContent=rule;r.classList.remove('hidden')}else r.classList.add('hidden');document.getElementById('powerOptions').innerHTML=buttons.join('');go('power')}
function playerButtons(cb,exclude=[],includeSelf=true,allowed=null){return S.players.map((p,i)=>({p,i})).filter(x=>!exclude.includes(x.i)&&(includeSelf||x.i!==S.current)&&(!allowed||allowed.includes(x.i))).map(x=>`<button class="btn btn-secondary" onclick="${cb}(${x.i})"><span>${escapeHtml(x.p.name)}${teamMode()?` · ${teamName(x.p.team)}`:''}</span><span>${powerIcons(x.p)||'⚽'}</span></button>`)}
function rivalButtons(cb){return playerButtons(cb,[S.current],false,opposingPlayers(S.current))}
function mateButtons(cb,includeSelf=true){return playerButtons(cb,[],includeSelf,teammatePlayers(S.current,includeSelf))}
function enterCurrentContent(){if(!S.currentContent)return;let ctx=S.turnCtx||{};let ev=S.currentContent.event;if(ctx.repeated&&!ctx.repeatHandled){ctx.repeatHandled=true;S.turnCtx=ctx;return showPower('🔁','BLOQUE REPETIDO','Esta consigna ya apareció en la partida. Podés repetirla o pedir una variante de la misma categoría y dificultad.',[`<button class="btn btn-primary" onclick="playRepeatedOriginal()">JUGAR IGUAL</button>`,`<button class="btn btn-secondary" onclick="playRepeatedVariant()">USAR VARIANTE</button>`],'La variante conserva el evento del bloque físico, pero cambia la consigna.','ANTI-REPETICIÓN')}
if(ctx.redActive&&ev&&ev!=='DADO'){ctx.eventDisabled=true;ctx.eventHandled=true;S.turnCtx=ctx;return showPower('🟥','ROJA','La Roja anula el poder especial de este bloque durante este turno.',[`<button class="btn btn-primary" onclick="continueToChallenge()">JUGAR SIN PODER</button>`],'El dado no se considera ayuda y sigue funcionando.','ESTADO NEGATIVO')}
if(ctx.eventHandled||!ev||ev==='DADO'||['REMONTADA','ROJA','PENALES','FINAL'].includes(ev))return continueToChallenge();
ctx.eventHandled=true;S.turnCtx=ctx;
if(ev==='CAPITAN'){ctx.powerStage='PRE_OPTIONAL';return showPower('⭐','CAPITÁN','Elegí a una persona para que pueda ayudarte con esta consigna.',[...teamMode()?mateButtons('setCaptainHelper',false):playerButtons('setCaptainHelper',[S.current],false),`<button class="btn btn-ghost" onclick="continueToChallenge()">JUGAR SOLO</button>`],'La respuesta cuenta para el jugador del turno.')}
if(ev==='HINCHADA'){ctx.powerStage='PRE_OPTIONAL';return showPower('📣','HINCHADA',teamMode()?'Todo tu equipo puede ayudarte durante esta consigna.':'Todos pueden ayudarte durante esta consigna.',[`<button class="btn btn-primary" onclick="activateHinchada()">ACTIVAR HINCHADA</button>`],'El resultado sigue perteneciendo al jugador del turno.')}
if(ev==='CONTRAATAQUE'){ctx.powerStage='PRE_CONTRA';return showPower('⚡','CONTRAATAQUE','Mandá esta consigna a un rival. Si falla, vos ganás 1 punto bonus; si acierta, el rival se lleva el mérito.',teamMode()?rivalButtons('setContraTarget'):playerButtons('setContraTarget',[S.current],false),'En Eliminación, el rival pierde una vida si falla.')}
if(ev==='EL_10'){ctx.powerStage='PRE_EL10';return showPower('🔟','EL 10','Elegí quién responde por vos. El resultado de la jugada sigue siendo tuyo.',teamMode()?mateButtons('setEl10Responder',true):playerButtons('setEl10Responder',[],true),'Ideal para poner la pelota en manos del especialista.')}
if(ev==='LA_COPA'){let p=S.players[S.current];if(!p.powers.includes('COPA')){p.powers.push('COPA');ctx.copaJustEarned=true}ctx.powerStage='PRE_OPTIONAL';S.turnCtx=ctx;save();return showPower('🏆','LA COPA','Guardaste LA COPA para salvar una jugada fallada en un turno futuro.',[`<button class="btn btn-primary" onclick="continueToChallenge()">GUARDAR Y JUGAR</button>`],'No puede consumirse en la misma jugada en la que se obtiene.','PODER GUARDABLE')}
continueToChallenge()}
