const APP_RELEASE='RC1';
let deferredInstallPrompt=null;
function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
function updateNetworkStatus(){let b=document.getElementById('networkBanner');if(!b)return;b.classList.toggle('show',!navigator.onLine)}
function updateInstallUI(){let btn=document.getElementById('installBtn'),hint=document.getElementById('installHint');if(!btn||!hint)return;if(isStandalone()){btn.style.display='none';hint.classList.remove('show');return}let ios=/iphone|ipad|ipod/i.test(navigator.userAgent);if(deferredInstallPrompt){btn.style.display='block';btn.textContent='📲 INSTALAR APP';hint.classList.remove('show')}else if(ios){btn.style.display='block';btn.textContent='📲 AGREGAR A INICIO';hint.textContent='En iPhone/iPad: tocá Compartir y elegí “Agregar a pantalla de inicio”.';hint.classList.add('show')}else{btn.style.display='none';hint.classList.remove('show')}}
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice}catch(e){}deferredInstallPrompt=null;updateInstallUI();return}let ios=/iphone|ipad|ipod/i.test(navigator.userAgent);if(ios){let hint=document.getElementById('installHint');hint.textContent='Tocá Compartir en Safari y elegí “Agregar a pantalla de inicio”.';hint.classList.add('show')}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;updateInstallUI()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;updateInstallUI()});
window.addEventListener('online',updateNetworkStatus);window.addEventListener('offline',updateNetworkStatus);
function initReleaseShell(){updateNetworkStatus();updateInstallUI();let splash=document.getElementById('bootSplash');requestAnimationFrame(()=>setTimeout(()=>splash?.classList.add('hide'),180));if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol)){navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}}

async function bootGameData(){const names=["meta.json","content_facil_1.json","content_facil_2.json","content_facil_3.json","content_leyenda_1.json","content_leyenda_2.json","content_leyenda_3.json","content_medio_1.json","content_medio_2.json","content_medio_3.json","penalties_facil_1.json","penalties_facil_2.json","penalties_leyenda_1.json","penalties_leyenda_2.json","penalties_medio_1.json","penalties_medio_2.json"];const rs=await Promise.all(names.map(x=>fetch('./data/'+x)));if(rs.some(r=>!r.ok))throw new Error('No pude cargar la biblioteca del juego.');const vals=await Promise.all(rs.map(r=>r.json()));const meta=vals[0],chunks=vals.slice(1);DB={meta,content:chunks.filter((_,i)=>names[i+1].startsWith('content_')).flat(),penalties:chunks.filter((_,i)=>names[i+1].startsWith('penalties_')).flat()};let storedPrefs=prefs();if(Object.keys(storedPrefs).length)S.settings={...S.settings,...storedPrefs};normalizeState();renderFormats();renderModes();renderDiffs();renderPlayers();renderSettings();updateResumeButton();initReleaseShell()}
bootGameData().catch(e=>{console.error(e);document.getElementById('bootSplash')?.classList.add('hide');const st=document.getElementById('licenseState');if(st)st.textContent='⚠️ No pude cargar la biblioteca del juego. Volvé a intentarlo con conexión.'});
