let audioCtx=null;
function applyFxSetting(){document.body?.classList.toggle('fx-off',S.settings?.animations===false)}
function prefs(){try{return JSON.parse(localStorage.getItem('torreAmericaPrefs')||'{}')}catch(e){return {}}}
function savePrefs(){localStorage.setItem('torreAmericaPrefs',JSON.stringify(S.settings));applyFxSetting()}
function renderSettings(){['Audio','Vibration','Animations'].forEach(k=>{let key=k.toLowerCase(),el=document.getElementById('sw'+k);if(el)el.classList.toggle('on',S.settings[key]!==false)})}
function toggleSetting(key){S.settings[key]=S.settings[key]===false;savePrefs();renderSettings();if(key==='audio'&&S.settings.audio)playFx('click',true)}
function getAudioCtx(){if(!audioCtx){let A=window.AudioContext||window.webkitAudioContext;if(A)audioCtx=new A()}if(audioCtx?.state==='suspended')audioCtx.resume();return audioCtx}
function tone(ctx,freq,start,dur,gain=.04,type='sine'){let o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);g.gain.setValueAtTime(0.0001,start);g.gain.exponentialRampToValueAtTime(gain,start+.008);g.gain.exponentialRampToValueAtTime(0.0001,start+dur);o.connect(g).connect(ctx.destination);o.start(start);o.stop(start+dur+.02)}
function noise(ctx,start,dur=.22,gain=.018){let len=Math.max(1,Math.floor(ctx.sampleRate*dur)),buf=ctx.createBuffer(1,len,ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);let src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=buf;g.gain.value=gain;src.connect(g).connect(ctx.destination);src.start(start)}
function playFx(kind,force=false){if(!force&&S.settings?.audio===false)return;let ctx=getAudioCtx();if(!ctx)return;let t=ctx.currentTime+.01;try{if(kind==='click')tone(ctx,520,t,.045,.018,'square');else if(kind==='whistle'){tone(ctx,1500,t,.13,.035,'sine');tone(ctx,1900,t+.10,.19,.032,'sine')}else if(kind==='goal'){noise(ctx,t,.38,.025);tone(ctx,520,t,.12,.05);tone(ctx,660,t+.11,.12,.05);tone(ctx,820,t+.22,.18,.055)}else if(kind==='save'){tone(ctx,220,t,.14,.045,'square');tone(ctx,160,t+.10,.16,.035,'square')}else if(kind==='power'){tone(ctx,440,t,.09,.028);tone(ctx,660,t+.08,.12,.032)}else if(kind==='red'){tone(ctx,180,t,.18,.05,'sawtooth')}else if(kind==='dice'){tone(ctx,330,t,.05,.02,'square');tone(ctx,410,t+.06,.05,.02,'square');tone(ctx,510,t+.12,.08,.025,'square')}else if(kind==='tick')tone(ctx,880,t,.035,.015,'square');else if(kind==='win'){noise(ctx,t,.5,.025);[523,659,784,1047].forEach((f,i)=>tone(ctx,f,t+i*.11,.22,.05))}}catch(e){}}
function vibrate(pattern){if(S.settings?.vibration!==false&&navigator.vibrate)try{navigator.vibrate(pattern)}catch(e){}}
document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('#settings'))playFx('click')},{passive:true});

function save(){localStorage.setItem('torreAmericaGame',JSON.stringify(S));savePrefs()}
function resumeGame(){let x=localStorage.getItem('torreAmericaGame');if(!x)return alert('No hay una partida guardada.');try{S=JSON.parse(x);normalizeState();if(!S.playFormat)S.playFormat='FISICA';S.started=true;if(S.shootout){if(!S.shootout.currentPen)prepareShootoutKick();else{document.getElementById('shootReady').classList.remove('hidden');document.getElementById('shootContent').classList.add('hidden');document.getElementById('shootAnswer').classList.add('hidden');document.getElementById('shootActions').classList.add('hidden')}return go('shootout')}if(S.activePenalty){pen={...S.activePenalty};penOrigin=S.activePenalty.origin||'DICE';document.getElementById('penPlayer').textContent='Patea '+S.players[S.current].name;document.getElementById('penReady').classList.remove('hidden');document.getElementById('penContent').classList.add('hidden');document.getElementById('penAnswer').classList.add('hidden');document.getElementById('penActions').classList.add('hidden');return go('penalty')}if(S.lastOutcome&&S.currentContent){document.getElementById('resultIcon').textContent=S.lastOutcome.ok?'⚽':'🧤';document.getElementById('resultTitle').textContent=S.lastOutcome.ok?'¡GOOOL!':'ATAJADA';document.getElementById('resultText').textContent='Jugada recuperada. Continuá para cerrar el turno.';return go('result')}if(S.currentContent&&S.turnCtx){let st=S.turnCtx.powerStage;if(st==='SECOND_CHANCE')return offerSecondChance(S.turnCtx.secondChanceSource||'REPLAY');if(['PRE_CONTRA','PRE_EL10','POST_RED','POST_PENALES','POST_FINAL','POST_DONE'].includes(st))return powerBack();return enterCurrentContent()}go('turn')}catch(e){alert('No pude recuperar esa partida.') }}
