(()=>{
const A={rain:'https://upload.wikimedia.org/wikipedia/commons/b/bb/Rain_and_thunder_%281%29.ogg',knock:'https://upload.wikimedia.org/wikipedia/commons/7/7c/Door_knocker_audio.ogg',bell:'https://upload.wikimedia.org/wikipedia/commons/1/13/Old_school_bell_4.ogg'};
let mode=localStorage.getItem('c002_audio_mode')||'',vol=+(localStorage.getItem('c002_audio_volume')||.32),rain,bell,knock,timers=[];
const css=`.a181-choice{position:fixed;inset:0;z-index:12000;background:#000e;display:grid;place-items:center;padding:18px}.a181-card{width:min(650px,100%);border:1px solid #735235;border-radius:20px;background:radial-gradient(circle at 80% 0,#28190f,#0b0a09 62%);padding:24px;box-shadow:0 30px 100px #000}.a181-card h2{font-family:Georgia,serif;font-size:2rem;margin:5px 0 8px}.a181-card p{color:#ad9d8a;line-height:1.5}.a181-opts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.a181-opts button{border:1px solid #5c432d;background:#100e0c;color:#e8d7ba;border-radius:11px;padding:13px;text-align:left;cursor:pointer}.a181-opts b{display:block}.a181-opts span{display:block;color:#958777;font-size:.68rem;margin-top:5px}.a181-fab{position:fixed;right:12px;top:12px;z-index:11900;border:1px solid #6b5034;background:#0b0a09e8;color:#ead9bb;border-radius:999px;padding:9px 12px;font:800 11px system-ui;cursor:pointer}.a181-panel{display:none;position:fixed;right:12px;top:54px;z-index:11910;width:260px;border:1px solid #5e452f;border-radius:13px;background:#0d0c0b;padding:12px;box-shadow:0 18px 50px #000b}.a181-panel.on{display:block}.a181-row{display:flex;justify-content:space-between;align-items:center;gap:8px;border-top:1px solid #30261e;padding:8px 0;font-size:.72rem;color:#aa9c8b}.a181-row:first-child{border:0}.a181-row button{border:1px solid #5a432f;background:#15110e;color:#e8d7ba;border-radius:999px;padding:5px 8px;cursor:pointer}.a181-note{font-size:.62rem;color:#766a60;line-height:1.35}@media(max-width:620px){.a181-opts{grid-template-columns:1fr}.a181-card{padding:18px}.a181-fab{right:8px;top:8px}.a181-panel{right:8px;top:50px}}`;
document.head.insertAdjacentHTML('beforeend','<style>'+css+'</style>');
function init(){if(rain)return;rain=new Audio(A.rain);rain.loop=true;rain.preload='auto';bell=new Audio(A.bell);knock=new Audio(A.knock);[bell,knock].forEach(x=>x.preload='auto');setVol()}
function setVol(){if(rain)rain.volume=vol*.42;if(bell)bell.volume=vol*.7;if(knock)knock.volume=vol*.9}
function save(){localStorage.setItem('c002_audio_mode',mode);localStorage.setItem('c002_audio_volume',vol);paint()}
function clear(){timers.forEach(clearTimeout);timers=[]}
function cancel(){clear();try{speechSynthesis.cancel()}catch{}duck(0)}
function duck(on){if(rain)rain.volume=vol*(on?.16:.42)}
function ambient(){init();if(mode==='silent')return;rain.play().catch(()=>{})}
function voice(alt=false){const v=speechSynthesis.getVoices?.()||[],m=v.find(x=>/^es-AR/i.test(x.lang))||v.find(x=>/^es/i.test(x.lang))||null;if(!alt)return m;return v.find(x=>/^es/i.test(x.lang)&&x!==m)||m}
function speak(t,opt={}){if(mode!=='full'||!t||!window.speechSynthesis)return;cancel();const u=new SpeechSynthesisUtterance(t);u.lang='es-AR';u.rate=opt.rate||.9;u.pitch=opt.tape?.78:(opt.pitch||.96);u.volume=Math.min(1,vol*1.55);const v=voice(!!opt.tape);if(v)u.voice=v;duck(1);u.onend=u.onerror=()=>duck(0);speechSynthesis.speak(u)}
function fx(a,stop=0){if(mode==='silent'||!a)return;try{a.pause();a.currentTime=0;a.play().catch(()=>{});if(stop)timers.push(setTimeout(()=>{a.pause();a.currentTime=0},stop))}catch{}}
function blackout(){if(mode==='silent')return;init();cancel();duck(1);timers.push(setTimeout(()=>fx(bell,900),500),setTimeout(()=>fx(knock),2100),setTimeout(()=>{if(mode==='full')speak('Silencio.',{rate:.72,pitch:.82});else duck(0)},4100))}
function narrateScene(){if(mode!=='full'||!window.SCENES)return;const x=SCENES[window.sceneIndex??0];if(!x)return;cancel();if(x.cls==='blackout'){speak(`${x.time}. ${x.title}`,{rate:.82,pitch:.92});timers.push(setTimeout(blackout,1800));return}let t=[x.time,x.title,...x.lines].filter(Boolean).join('. ').replace(/QUIÉN/g,'quién').replace(/DÓNDE/g,'dónde').replace(/CON QUÉ/g,'con qué');timers.push(setTimeout(()=>speak(t,{rate:(window.sceneIndex??0)===0?.84:.91}),220))}
function choose(){if(document.getElementById('a181choice'))return;const d=document.createElement('div');d.id='a181choice';d.className='a181-choice';d.innerHTML=`<div class="a181-card"><div class="eyebrow">HOTEL ORFEO · EXPERIENCIA SONORA</div><h2>¿Cómo querés entrar al expediente?</h2><p>Esta beta incorpora lluvia y tormenta reales, efectos puntuales y narración de prueba. Podés cambiarlo después.</p><div class="a181-opts"><button data-m="full"><b>🔊 SONIDO + VOZ</b><span>Ambiente, efectos y narración.</span></button><button data-m="ambience"><b>🌧️ SOLO AMBIENTE</b><span>Lluvia, tormenta y efectos.</span></button><button data-m="silent"><b>🔇 EN SILENCIO</b><span>Experiencia visual.</span></button></div></div>`;document.body.appendChild(d);d.querySelectorAll('button').forEach(b=>b.onclick=()=>{mode=b.dataset.m;save();d.remove();if(mode!=='silent')ambient();openNow()})}
function paint(){const b=document.getElementById('a181fab');if(b)b.textContent=(mode==='silent'?'🔇':'🔊')+' AUDIO';const m=document.getElementById('a181mode');if(m)m.textContent=mode==='full'?'SONIDO + VOZ':mode==='ambience'?'SOLO AMBIENTE':'SILENCIO';const n=document.getElementById('a181narr');if(n)n.textContent=mode==='full'?'ON':'OFF';const r=document.getElementById('a181vol');if(r)r.value=Math.round(vol*100)}
function controls(){if(document.getElementById('a181fab'))return;document.body.insertAdjacentHTML('beforeend',`<button id="a181fab" class="a181-fab">AUDIO</button><div id="a181panel" class="a181-panel"><div class="a181-row"><span>Modo</span><button id="a181mode">—</button></div><div class="a181-row"><span>Narración</span><button id="a181narr">—</button></div><div class="a181-row"><span>Volumen</span><input id="a181vol" type="range" min="0" max="100"></div><div class="a181-note">La voz de esta beta depende del dispositivo. La versión final tendrá voces producidas para Narrador, León y Lucía.</div></div>`);document.getElementById('a181fab').onclick=()=>document.getElementById('a181panel').classList.toggle('on');document.getElementById('a181mode').onclick=()=>{cancel();mode=mode==='full'?'ambience':mode==='ambience'?'silent':'full';if(mode==='silent'){rain?.pause()}else ambient();save()};document.getElementById('a181narr').onclick=()=>{mode=mode==='full'?'ambience':'full';if(mode!=='full')cancel();else if(document.getElementById('cinema')?.classList.contains('open'))narrateScene();save()};document.getElementById('a181vol').oninput=e=>{vol=+e.target.value/100;setVol();save()};paint()}
const baseOpen=window.openCinema,baseRender=window.renderCinema,baseClose=window.closeCinema;
function openNow(){ambient();baseOpen();setTimeout(narrateScene,100)}
window.openCinema=()=>{if(!mode)choose();else openNow()};
window.renderCinema=()=>{baseRender();narrateScene()};window.closeCinema=(x=false)=>{cancel();baseClose(x)};
const major=window.c002ShowMajorEvent;if(typeof major==='function')window.c002ShowMajorEvent=e=>{major(e);if(mode==='silent')return;const t=String(e?.payload?.body||'');if(e?.event_type==='c002_audio')setTimeout(()=>speak(t,{tape:1,rate:.8}),260);else if(e?.event_type==='c002_room317')setTimeout(()=>speak('Habitación tres diecisiete desbloqueada. La habitación nunca dejó de existir. Fue sellada.',{rate:.82}),260);else if(e?.event_type==='c002_blackout')setTimeout(()=>speak(t,{rate:.84}),260);else if(e?.event_type==='c002_polaroid')setTimeout(()=>speak('Polaroid revelada. '+t,{rate:.86}),260)};
const recon=window.c002RenderReconstruction;if(typeof recon==='function')window.c002RenderReconstruction=()=>{recon();if(mode==='full')try{const x=c002ReconData()[c002ReconStep];if(x)setTimeout(()=>speak(`${x.k}. ${x.title}. ${x.text}`,{rate:x.post?.78:.88,pitch:x.post?.86:.95}),220)}catch{}};
addEventListener('DOMContentLoaded',()=>{init();controls();const f=document.querySelector('footer');if(f)f.insertAdjacentHTML('beforebegin','<section class="section"><div class="notice"><b>AUDIO · BETA</b><br>Ambiente y efectos reales de dominio público/CC0 desde Wikimedia Commons. La narración actual usa la voz disponible en el dispositivo.</div></section>')});
})();