from pathlib import Path
p=Path('admin-licencias/index.html')
s=p.read_text(encoding='utf-8')
old='.miniBtn{border:1px solid #444951;background:#22252a;color:#fff;border-radius:9px;padding:7px 9px;font-size:.65rem;font-weight:900;cursor:pointer}'
new=old+'.miniBtn.danger{border-color:#7a3c3c;background:#35191b;color:#ffc2ba}.miniBtn.success{border-color:#2d6950;background:#17362f;color:#a8e4d4}.miniBtn:disabled{opacity:.45;cursor:not-allowed}'
assert s.count(old)==1, f'CSS anchor mismatch {s.count(old)}'
s=s.replace(old,new,1)
start=s.index('function renderHistory(){')
end=s.index('\nlet historyMessageLicense=',start)
newblock='''function renderHistory(){const q=$('search').value.trim().toLowerCase();const rows=historyRows.filter(r=>!q||[r.product_name,r.product_code,r.license_key,r.activation_code,r.owner_email,r.order_ref,r.sale_ref,r.channel_name].join(' ').toLowerCase().includes(q));if(!rows.length){$('history').innerHTML='<div class="empty">No hay accesos que coincidan con la búsqueda.</div>';return}$('history').innerHTML=rows.map((r,i)=>{const canDelete=!r.activated_at&&Number(r.devices_used||0)===0;const stateBtn=(r.status==='revoked'||r.status==='expired')?`<button class="miniBtn success" data-reactivate="${i}">Reactivar</button>`:`<button class="miniBtn danger" data-revoke="${i}">Dar de baja</button>`;const delBtn=canDelete?`<button class="miniBtn danger" data-delete="${i}">Eliminar</button>`:'';return `<article class="row"><div><b>${esc(r.product_name)}</b><small>${esc(r.product_code)} · ${esc(r.channel_name||r.source)}</small></div><div><span class="badge ${esc(r.status)}">${esc(statusLabel(r.status))}</span><small>${r.devices_used||0} / ${r.device_limit||2} dispositivos</small><small>Vigencia: ${esc(r.duration_label||durationText(r))}</small></div><div><b class="mono">${esc(r.sale_ref||'—')}</b><small>${new Date(r.created_at).toLocaleDateString('es-AR')}</small></div><div><b>${esc(r.owner_email||'Aún sin email')}</b><small>${r.expires_at?'Vence '+new Date(r.expires_at).toLocaleDateString('es-AR'):'Vigencia inicia al activar'}</small></div><div class="rowActions"><button class="miniBtn" data-message="${i}">Ver mensaje</button><button class="miniBtn" data-copy="${i}">Copiar código</button>${stateBtn}${delBtn}</div></article>`}).join('');[...$('history').querySelectorAll('[data-message]')].forEach(b=>b.onclick=()=>showHistoryMessage(rows[+b.dataset.message]));[...$('history').querySelectorAll('[data-copy]')].forEach(b=>b.onclick=async()=>{const r=rows[+b.dataset.copy];await copyText(r.license_key);b.textContent='Copiado';setTimeout(()=>b.textContent='Copiar código',1000)});[...$('history').querySelectorAll('[data-revoke]')].forEach(b=>b.onclick=()=>adminLicenseAction('revoke',rows[+b.dataset.revoke]));[...$('history').querySelectorAll('[data-reactivate]')].forEach(b=>b.onclick=()=>adminLicenseAction('reactivate',rows[+b.dataset.reactivate]));[...$('history').querySelectorAll('[data-delete]')].forEach(b=>b.onclick=()=>adminLicenseAction('delete',rows[+b.dataset.delete]))}
async function adminLicenseAction(action,r){let ok=false;if(action==='revoke')ok=confirm(`¿Dar de baja este acceso?\\n\\n${r.product_name}\\n${r.license_key}\\n\\nEl cliente dejará de poder usarlo, pero se conservará todo el historial.`);else if(action==='reactivate')ok=confirm(`¿Reactivar este acceso?\\n\\n${r.product_name}\\n${r.license_key}\\n\\nSi estaba vencido, se renovará por la vigencia configurada.`);else if(action==='delete'){const typed=prompt(`ELIMINACIÓN DEFINITIVA\\n\\n${r.product_name}\\n${r.license_key}\\n\\nSolo puede borrarse si nunca fue usado. Escribí BORRAR para confirmar:`);ok=typed==='BORRAR'}if(!ok)return;msg('historyMsg','Procesando…','');try{const data=await callAdmin({action,license_id:r.id});msg('historyMsg',data.message||'Operación completada.','good');await loadHistory()}catch(e){msg('historyMsg',e.message||String(e),'bad')}}'''
s=s[:start]+newblock+s[end:]
assert 'data-revoke=' in s and 'data-reactivate=' in s and 'data-delete=' in s
assert "adminLicenseAction('revoke'" in s
p.write_text(s,encoding='utf-8')
print('Admin license actions patch OK')
